### ISSUE TITLE
Homburg: solution: just have everybody register names

### ISSUE THREAD

**Issue by Abhayakara** [Abhayakara/draft-tldr-sutld-ps#1]
Problems with this solution: if a name expires accidentally, mayhem. if still in use but owner dies, mayhem.

Implementation: need agreement with ICANN that they are willing to tell registrars to do special-use allocations for the IETF to address these two problems.

Add to problem statement: The organization registers and then dies problem
Does this belong at all in the problem statement, or is this a solution with problems?

Acknowledgements: Philip Homburg

**Comment by wkumari** [comment]
Classifying as solution with problems.

Closing because not applicable  to *this* document.
