### ISSUE TITLE
AUTH48: Add adpjka authors to ack section

### ISSUE THREAD

**Issue by Abhayakara** [Abhayakara/draft-tldr-sutld-ps#100]
"We would also like to thanks the authors of
draft-adpkja-dnsop-special-names-problem, including Alain Durand,
Geoff Huston, Peter Koch and Joe Abley for significant amounts of
help."
I personally think that this can be added at AUTH48, but, of course,
will defer to you.

**Comment by wkumari** [comment]
Updated (Ralph) text - placing here so it doesn't get lost:

"We would also like to acknowledge the authors of
draft-adpkja-dnsop-special-names-problem, including Alain Durand,
Geoff Huston, Peter Koch and Joe Abley, for their efforts to frame the
issues and engage the working group, as well as their contributions to the list of issues from their document [draft-adpkja-dnsop-special-names-problem]."

**Comment by wkumari** [comment]
Closing old issues...
