### ISSUE TITLE
Reminder for AUTH48 - Incorrect description on Reference.

### ISSUE THREAD

**Issue by wkumari** [Abhayakara/draft-tldr-sutld-ps#101]
I believe correct reference, but incorrect "title" for reference.
 
Also to add Mats Dufberg to acknowledgements section.

--------
I am reading the draft Special-Use Domain Names Problem Statement (draft-ietf-dnsop-sutld-ps-08) and I think that one reference points at the wrong data:
 
   [SDO-ICANN-DAG]
              Internet Assigned Numbers Authority, "Special-Use Domain
              Names registry", October 2015,
              <https://newgtlds.icann.org/en/applicants/agb/guidebook-
              full-04jun12-en.pdf>.
 
The URL points at AGB, but that seems wrong, but the description refer to the special Registry. But from the text I expected some document.

**Comment by Abhayakara** [comment]
Good catch. Now to remember to fix it...

**Comment by wkumari** [comment]
Closing OBE events to clean up my Issues dashboard.
