### ISSUE TITLE
How does a name get identified as "commandeered"?

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#11]
from John Levine
https://www.ietf.org/mail-archive/web/dnsop/current/msg19167.html

In the problem paragraph that starts at the bottom of page 6, on
domain names that have been commandeered, I'd like it to say that
there is no agreement on how to decide that a name has been
comandeered, nor if or how to revisit a name to decide that it's been
uncomandeered.

(For that last, I'm thinking about .BELKIN, where the routers that
leak the name will eventually all fail, or .CORP where people may use
it less now that CAs don't sign certs any more.)

**Comment by rdroms** [comment]
I agree with the point John is trying to make, but I think it's out of scope for this document.  I think we can leave this document as noting that domain names have been commandeered, the situation should be addressed, but the process for doing so is out of scope for this document.  Proposed:

OLD:

   o  There are several Domain Name TLDs that have been commandeered
      without due process for a variety of purposes [SDO-ICANN-COLL].
      The status of these names need to be clarified and recorded to
      avoid future disputes about their use. [ Ed note: We note that
      DNSOP has previously discussed some of these in draft-chapin-
      additional-reserved-tlds-02, and decided not to adopt the draft -
      https://www.ietf.org/mail-archive/web/dnsop/current/msg14887.html
      .  The authors are not recommending that DNSOP revisit this,
      rather that is needs to be addressed in some venue. ]

NEW:

   o  There are several Domain Name TLDs that have been commandeered
      without due process for a variety of purposes [SDO-ICANN-COLL].
      The status of these names need to be clarified and recorded to
      avoid future disputes about their use.  The specific process for
      addressing this issue is out of scope for this document.  [ Ed note: We note that
      DNSOP has previously discussed some of these in draft-chapin-
      additional-reserved-tlds-02, and decided not to adopt the draft -
      https://www.ietf.org/mail-archive/web/dnsop/current/msg14887.html
      .  The authors are not recommending that DNSOP revisit this,
      rather that is needs to be addressed in some venue. ]

**Comment by wkumari** [comment]
LGTM

**Comment by rdroms** [comment]
Turns out I've suggested new text for this text in #33 and #41.  I think #41 is best.

**Comment by rdroms** [comment]
Confirming - I suggest the text in #41 to address #41, #33 and #11

**Comment by rdroms** [comment]
Closed with #41
