### ISSUE TITLE
Add DNSSEC to text

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#12]
From John Levine
https://www.ietf.org/mail-archive/web/dnsop/current/msg19167.html

I'd also like a mention of DNSSEC.  DNSSEC is intended to provide a
signature chain from the root to any leaf, but there is no way to
chain to a SUTLD.  There's also no agreement what to do with DNSSEC
and existing SUTLDs, whether to have DNSSEC say they don't exist, or
to create some sort of unsigned pseudo-delegation, or something else.

**Comment by rdroms** [comment]
DNSSEC does seem to be a problem, as evidenced by the lengthy discussion on the dnsop mailing list.

Suggested new bullet:

* The use of DNSSEC with SUDNs is an open issue.  There is no consensus or guidance about how to use DNSSEC with various classes of SUDNs.  Considerations in the use of DNSSEC with SUDNs include:
  o What class of SUDN is under consideration: non-DNS, locally served zone, other?
  o Does the SUDN require a signed or unsigned delegation in the root zone?
  o Is there a process through which the IETF can cause a delegation in the root zone to be instantiated?
  o What are the recommended practices for using DNS with the specific SUDN?

**Comment by rdroms** [comment]
Wordsmithed:


* The use of DNSSEC with SUDNs is an open issue. There is no consensus or guidance about how to use DNSSEC with various classes of SUDNs. Considerations in the use of DNSSEC with SUDNs include:
o What class of SUDN is under consideration: non-DNS, locally served zone, other?
o Does the SUDN require a delegation in the root zone; if so, should that delegation be signed or unsigned?
o Is there a process through which the IETF can cause a delegation in the root zone to be instantiated?
o What are the recommended practices for using DNS with the specific SUDN?

**Comment by wkumari** [comment]
From the DNSOP Interim meeting on Special Use Names call, it was suggested that we note that DNSSEC constrains the solutions / what you can do.
If you want this to be a DNS Special Use Name, you have to keep DNSSEC in mind.

**Comment by marka63** [comment]
and the constraints work both ways to prevent invalid responses being generated when following instructions for handling the special name.
e.g. 
1) since we expect RFC 1918 names to be looked up using the DNS there needed to exist a delegation at the top of the namespace with a insecure delegation somewhere between the
root and that delegation inclusive so that DNSSEC just works for private clients and there is
no NXDOMAIN returned for any parent name.
2) if a delegation in prohibited in the global namespace recursive server MUST NOT synthesis NXDOMAIN responses.  (We got this wrong for .onion.)

**Comment by rdroms** [comment]
We still need to review the previous comment against the candidate text suggested above.

**Comment by Abhayakara** [comment]
In bullet point 3, s/Is there a process/A process would be required/
In 2, before question mark, could add "(if there is no delegation, then this implies that there is a secure denial of existence for that zone.   This would not be appropriate for a name being resolved using the DNS protocol.)"

**Comment by rdroms** [comment]
* The use of DNSSEC with SUDNs is an open issue. There is no consensus or guidance about how to use DNSSEC with various classes of SUDNs. Considerations in the use of DNSSEC with SUDNs include:
o What class of SUDN is under consideration: non-DNS, locally served zone, other?
o Does the SUDN require a delegation in the root zone; if so, should that delegation be signed or unsigned (if there is no delegation, then this implies that there is a secure denial of existence for that zone. This would not be appropriate for a name being resolved using the DNS protocol.)?
o A process would be required through which the IETF can cause a delegation in the root zone to be instantiated.
o What are the recommended practices for using DNS with the specific SUDN?

**Comment by rdroms** [comment]
Consensus to use final text; perhaps with wordsmithing.

**Comment by rdroms** [comment]
Edits completed
