### ISSUE TITLE
Spelling of Tor

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#13]
From Jeremy Rand
https://www.ietf.org/mail-archive/web/dnsop/current/msg19168.html

Trivial spelling nit: Sec. 4.2.2 says "unilateral use by the TOR
project".  The correct spelling is "Tor" (only the "T" in "Tor" should
be capitalized.)  Also, according to
https://www.torproject.org/docs/trademark-faq.html.en, "The Tor Project"
is the correct spelling of the phrase (all 3 words should have the
initial letter capitalized).

**Comment by wkumari** [comment]
Thank you,
Fixed.
