### ISSUE TITLE
Change SDO to "organizations"

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#14]
From Suzanne Woolf
https://www.ietf.org/mail-archive/web/dnsop/current/msg19170.html

1. I think for purposes of this document, ICANN and SSAC are not "standards organizations", just "organizations". I realize it's a debatable point in casual use (is ICANN's documentation of its processes for changing the root zone "standards"?) but I don’t think it applies within the usual meaning of the term for the IETF and other recognized SDOs.

**Comment by wkumari** [comment]
Thank you.

Fixed.
