### ISSUE TITLE
Check "names=DNS" assumption throughout document

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#15]
From Suzanne Woolf
https://www.ietf.org/mail-archive/web/dnsop/current/msg19170.html

Introduction

2. I like that the name/resolution distinction is clearly called out here. I’m not sure the names=DNS assumption has been entirely banished throughout but it’s definitely heading in the right direction.

**Comment by rdroms** [comment]
I took a scan through the document.  I don't see any additional text that assumes "name = DNS".  I don't have any edits to suggest in response to this issue.  OK to close?

**Comment by wkumari** [comment]
Ok with me...
