### ISSUE TITLE
Match number of "policies" and "that policy"

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#16]
From Suzanne Woolf
https://www.ietf.org/mail-archive/web/dnsop/current/msg19170.html

Introduction

3. STYLE/GRAMMAR: "....defined policies for adding to the registry, and made some suggestions about how that policy might be implemented." This should be "....defined a policy..." or "....about how those policies might be implemented."

**Comment by wkumari** [comment]
Thank you.

Fixed.
