### ISSUE TITLE
Define "default" or "assumed" use of domain names to be within DNS

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#19]
From Suzanne Woolf
https://www.ietf.org/mail-archive/web/dnsop/current/msg19170.html

Terminology

6. The terms are all defined relative to something we don't actually have a term for, but might need one. If we're talking here about "special use" names, what's a "normal" or "ordinary" or "expected" use, and how is a "special use" different? You seem to be answering that question but only by implication.

Possibly add something like "The default or assumed use of a domain name is initialization and resolution within the Domain Name System, which includes a single global resolution scope and the Domain Name System protocol (RFC 1034/1035). Such names are expected to be unique within the global domain namespace. A name intended for use in the internet or its defining protocols, following the construction rules for domain names, but not global in scope or resolved by DNS wire protocol, could be considered a 'special use' name."

We don't have a formal, consensus definition anywhere, but RFC 7719 takes a credible shot at a lot of what we need here, so you might mostly be able to get away with citing it.

**Comment by rdroms** [comment]
Well - I've been reviewing draft-ietf-dnsop-terminology-bis and RFC 7719; seems to me we ought to point to the RFC and reuse the terminology from those docs as much as possible - although there's not all that much overlap at present.

The definition of "domain name" from RFC 7719 seems OK to refer to from our document.  Interestingly, RFC 6761 defines "Special Use Domain Name" only informally and without an explicit reference to what is "special" about an SUDN.

Here's a proposal for rewriting the terminology section:

OLD:

2.  Terminology

   For the sake of brevity this document uses a number of abbreviations.
   These are expanded here:

   Domain Name  A name which serves as input to a name resolution
      process, for example 'EXAMPLE.ORG'.

   Domain Namespace  The set of all possible Domain Names.

   SUDN  Special Use Domain Name

   SUTLDN  Special-Use Top-Level Domain Name

   IANA  Internet Assigned Numbers Authority

   ICANN  Internet Corporation for Assigned Names and Numbers

NEW:

2.  Terminology

   This document uses the terminology defined in DNS Terminology
   [I-D.ietf-dnsop-terminology-bis].

   Domain Name  This document uses the term "Domain Name" as defined in
      DNS Terminology [RFC7719].

   Domain Namespace  The set of all possible Domain Names.

   Special-Use Domain Name  Domain Names are often assumed to be
      intended for resolution in the Global DNS naming system.  A
      special-use Domain Name is intended for resolution in some other
      naming system; for example, in a naming system that uses a non-DNS
      resolution protoco or one that uses a resolution context other
      than the DNS root zone.  The IANA Special-Use Domain Names
      registry contains some but not all of the Domain Names that are
      considered to be Special Use Domain Names.

   Special-Use Top-Level Domain Name  A Special-Use Domain Name that
      appears one layer below the root of the Domain Name graph.

   For the sake of brevity this document uses a number of abbreviations.
   These are expanded here:

   SUDN  Special-Use Domain Name 

   SUTLDN  Special-Use Top-Level Domain Name

   IANA  Internet Assigned Numbers Authority

   ICANN  Internet Corporation for Assigned Names and Numbers

**Comment by Abhayakara** [comment]
It seems like the definition of "special use domain names" is something for the introduction rather than the terminology section, since it's the focus of the document.   I think this is why I was so brief in the terminology section, but maybe I was also too brief in the introduction?

**Comment by rdroms** [comment]
It may be my PCD (Pedantic Compulsive Disorder) showing itself, which tells me there ought to be a definition of Special-Use Domain Names in the Terminology section.  If it seems redundant, we could add a reference back to the discussion in the Introduction?

**Comment by Abhayakara** [comment]
Yes, that seems fine.

**Comment by wkumari** [comment]
Yup.

**Comment by rdroms** [comment]
Re-reading the Intro and RFC 6761, it seems the definition for "Special-Use Domain Name" is the tautological (worse, circular?) definition: A Special-Use Domain Name is a Domain Name listed in the Special-Use Domain Name registry.

It might be good to have this level of precision to differentiate between designated Special-Use Domain Names and candidate Special-Use Domain Names.  Anyway, I'm going to make the change and am willing to pull it out or update it.

**Comment by rdroms** [comment]
(post-closure comment) Strikes me that we might want to note explicitly somewhere that there are domain names that are "special-use" but not listed in the SUDN registry.
