### ISSUE TITLE
Conrad:  SOLUTION: put the special-use domain name registry in the DNS

### ISSUE THREAD

**Issue by Abhayakara** [Abhayakara/draft-tldr-sutld-ps#2]
10.in-addr.arpa IN URI 10 1 "http://www.iana.org/go/rfc6761"
...
onion           IN URI 10 1 "http://www.iana.org/go/rfc7686"

separately:

ICANN already cedes change control of some subsets of the top-level namespace to other organizations, e.g. ISO for ccTLDs

**Comment by wkumari** [comment]
Fascinating idea, worth exploring in a solutions document.
Classifying as a solution, closing because not applicable  to *this* document.
