### ISSUE TITLE
Section 3 - clarify paragraphs 2 and 3

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#21]
From Suzanne Woolf
https://www.ietf.org/mail-archive/web/dnsop/current/msg19170.html

Problems associated with Special-Use Domain Names

8. I think para. 2 (bottom of page 3) and para. 3 (top of page 4) are a little confusing, even though I understand the rhetorical device of using the word "problem" 12 times in half a page. I wanted to see how you felt about that text before trying to rewrite it.

**Comment by rdroms** [comment]
I don't feel strongly about this text.  I don't find it confusing ... might suggest a couple of wordsmithing changes.  On the other hand, if Suz wants to suggest replacement text, I'd be happy to consider it.

**Comment by Abhayakara** [comment]
Hm, as I was trying to rephrase the one sentence in the paragraph that stood out as difficult, I think I understood where she is coming from.   How about this:

Special-Use names exist to solve a variety of problems.   This document attempts to enumerate all of the problems that have been identified to which special use names are a solution.   It also attempts to enumerate all of the problems that have been raised in the process of trying to use RFC 6761 as it was intended.

There is a broad diversity of opinion about this set of problems.   Not every participant agrees that each of the problems we enumerate here is actually a problem.   This document takes no position on the relative validity of the various problems that have been enumerated.   Its sole purpose is to enumerate those problems and provide the reader with context for thinking about them.

**Comment by rdroms** [comment]
This text seems much better to me.  I have one substantive suggestion (anticipating comments from eventual readers) and a couple of wordsmithing suggestions:

Special-Use Domain Names exist to solve a variety of problems. This
document has two goals: enumerate all of the problems that have been
identified to which Special Use Domain Names are a solution and
enumerate all of the problems that have been raised in the process of
trying to use RFC 6761 as it was intended.  As some of those problems
may fall into both categories, this document makes no attempt to
categorize the problems.

There is a broad diversity of opinion about this set of problems. Not
every participant agrees that each of the problems enumerate in this
document is actually a problem. This document takes no position on the
relative validity of the various problems that have been enumerated. Its
sole purpose is to enumerate those problems and provide the reader with
context for thinking about them and a context for future discussion of
solutions.

**Comment by Abhayakara** [comment]
WFM.   I would use a serial comma rather than two ands in the last sentence.

**Comment by wkumari** [comment]
... and for me.

**Comment by rdroms** [comment]
Fixed, with 2 changes to suggested text:

As Ted suggested, use serial comma in last sentence
s/sole purpose is/focused purposes are/ - there are actually three purposes listed

OLD:

   No assertion is made that any of these problems is more or less
   important than any other.  The point of this is simply to enumerate
   and briefly describe the problems that have been raised during
   discussions of the special-use name problem.  The degree of detail is
   intended to be sufficient that that participants in the discussion



Lemon, et al.            Expires August 3, 2017                 [Page 3]

Internet-Draft          Special-Use Names Problem           January 2017


   can agree that the problems they've raised have been adequately
   described, and no more.  These problems should not appear to every
   reader to all be problems: we intend to cover any problem that any
   participant considers a problem, not just those problems that
   everyone agrees are problems.

   In addition, no assertion is made that all of these problems must be
   addressed, or that, if we think they should be addressed, the IETF is
   the organization with competence to address them.  While each problem
   has one or more solutions, the solutions may in some cases be
   mutually contradictory, or may come with costs that do not justify
   the benefit that would be obtained from solving them.

NEW:

   Special-Use Domain Names exist to solve a variety of problems.  This
   document has two goals: enumerate all of the problems that have been
   identified to which Special Use Domain Names are a solution and
   enumerate all of the problems that have been raised in the process of
   trying to use RFC 6761 as it was intended.  As some of those problems
   may fall into both categories, this document makes no attempt to
   categorize the problems.

   There is a broad diversity of opinion about this set of problems.
   Not every participant agrees that each of the problems enumerate in
   this document is actually a problem.  This document takes no position
   on the relative validity of the various problems that have been
   enumerated.  Its focused purposes are to enumerate those problems.
   provide the reader with context for thinking about them and a context
   for future discussion of solutions.
