### ISSUE TITLE
Clarify importance of the "root of the Domain Namespace"

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#22]
From Suzanne Woolf
https://www.ietf.org/mail-archive/web/dnsop/current/msg19170.html

Problems associated with Special-Use Domain Names

9. The text "There are several different types of names in the root of the Domain Namespace" assumes the root is important-- that it's the mathematical root of a tree-- without quite saying so. Citing RFC 7719, sec. 2 is probably helpful here.

**Comment by rdroms** [comment]
Hm.  On reflection, it seems like this first bullet in the Problems section is more correctly an observation or a fact that then leads to specific problems.  Perhaps this text could be moved up near the discussion of Special-Use Domain Names, as an outcome of the fact of SUDNs and text that helps understand some of the specific problems in section 2.

**Comment by Abhayakara** [comment]
You're right, this is background information.   It's also not entirely correct, in the sense that it lets out the possibility of special-use names that are both "reserved by the IETF" _and_ "part of the public root zone."   And I don't like the last bullet—if we know of some other such thing, we should enumerate it, but I don't think we do, and the text implies that we've left out something we know, when we haven't.

**Comment by rdroms** [comment]
Updated bullet list:

      *  Reserved by the IETF for technical purposes

      *  Assigned by ICANN to the Global DNS root; some names reserved
         by the IETF for technical purposes may appear in the Global DNS
         root for reasons pertaining to the operation of the DNS

      *  ICANN Reserved Names; names that may not be applied for as TLDs
         (see [SDO-ICANN-DAG]Section 2.2.1.2.1, Reserved Names )

      *  Commandeered for use by other organizations

      *  Names that are unused and are available for assignment to one
         of the previous categories

**Comment by Abhayakara** [comment]
lgtm

**Comment by rdroms** [comment]
Based on the default font in my browser, I interpreted the first character of "lgtm" as 0x49, which left me scratching my head.  Makes more sense when I interpret it as 0x6C.

I suggest we move this list up between the 2nd and 3rd paragraphs of the Introduction, perhaps leading with a sentence like:

Based on current ICANN and IETF practice, including RFC 6761, there are
several different types of names in the root of the Domain Namespace:

  *  Reserved by the IETF for technical purposes

  *  Assigned by ICANN to the Global DNS root; some names reserved
     by the IETF for technical purposes may appear in the Global DNS
     root for reasons pertaining to the operation of the DNS

  *  ICANN Reserved Names; names that may not be applied for as TLDs
     (see [SDO-ICANN-DAG]Section 2.2.1.2.1, Reserved Names )

  *  Commandeered for use by other organizations

  *  Names that are unused and are available for assignment to one
     of the previous categories

**Comment by Abhayakara** [comment]
wfm

(hopefully that's less ambiguous... :)

**Comment by wkumari** [comment]
WFM

**Comment by wkumari** [comment]
Discussed with Ralph, changing bullet #2 to something like: 
ICANN Reserved Names; names that may not be applied for as TLDs
    (see [SDO-ICANN-DAG]Section 2.2.1.2.1, Reserved Names, Section 2.2.1.4.1 Treatment of Country or Territory Names, et all   )

**Comment by rdroms** [comment]
OLD (was in section 3):

   o  There are several different types of names in the root of the
      Domain Namespace:

      *  Reserved by the IETF for technical purposes

      *  Assigned by ICANN to the public DNS root

      *  ICANN Reserved Names; names that may not be applied for as a
         TLD (see [SDO-ICANN-DAG]Section 2.2.1.2.1, Reserved Names )

      *  Commandeered for use by other organizations

      *  Not a member of any other category

NEW (now in section 1, 3rd para):

   Based on current ICANN and IETF practice, including RFC 6761, there
   are several different types of names in the root of the Domain
   Namespace:

   o  Reserved by the IETF for technical purposes

   o  Assigned by ICANN to the public DNS root; some names reserved by
      the IETF for technical purposes may appear in the Global DNS root
      for reasons pertaining to the operation of the DNS

   o  ICANN Reserved Names; names that may not be applied for as TLDs
      (see [SDO-ICANN-DAG], Section 2.2.1.2.1, Reserved Names,
      Section 2.2.1.4.1, Treatment of Country or Territory Names, et
      al.)

   o  Commandeered for use by other organizations

   o  Names that are unused and are available for assignment to one of
      the previous categories
