### ISSUE TITLE
Match number of "names" and "a TLD"

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#23]
From Suzanne Woolf
https://www.ietf.org/mail-archive/web/dnsop/current/msg19170.html

Problems associated with Special-Use Domain Names

10. STYLE/GRAMMAR: "names that may not be applied for as a TLD" -> "....applied for as TLDs"

**Comment by wkumari** [comment]
Thank you.

Done.
