### ISSUE TITLE
Replacement for "commandeer" (2 issues)

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#24]
From Suzanne Woolf
https://www.ietf.org/mail-archive/web/dnsop/current/msg19170.html

Problems associated with Special-Use Domain Names

11. STYLE/GRAMMAR: I wouldn't be surprised if the word "commandeer" made some readers uncomfortable; it's got an implication of illegitimacy.

-18. "Commandeer" again has some questionable connotations. Still not sure of a better word, but the .onion RFC might provide one.

**Comment by rdroms** [comment]
Yeah, "commandeer" might attract unnecessary attention away from the rest of the document.  How about "used without following established processes"?  I'm OK with retaining "commandeered" for brevity.

**Comment by Abhayakara** [comment]
I think your proposed change is good.

**Comment by wkumari** [comment]
+1 for "used without following established processes". I liked "commandeered" (take possession of (something) without authority), but I might have watched too many episodes of cheesy 80's cop shows....

**Comment by rdroms** [comment]
I made those changes, not all a direct replacement of "commandeer" with "used without following established processes":

*  Commandeered for use by other organizations

o  Used by other organizations without following established
    processes

-----

o  Organizations do in fact sometimes commandeer subsets of the
    namespace.  Reasons a third party might do this include:

o  Organizations do in fact sometimes use subsets of the Domain
     Namespace without following established processes.  Reasons a
     third party might do this include:

-----

    o  There are several Domain Name TLDs that have been commandeered
       without due process for a variety of purposes [SDO-ICANN-COLL].

    o  There are several Domain Name TLDs that are in use without due
       process for a variety of purposes [SDO-ICANN-COLL].  The status of

-----

     Additionally, ".home" is an example of an attempt to reuse a Domain
    Name that has already been commandeered for other purposes
    [SDO-ICANN-COLL], which further complicates the situation.

     Additionally, ".home" is an example of an attempt to reuse a Domain
    Name that has already been put into use for other purposes without
    following established processes[SDO-ICANN-COLL], which further
    complicates the situation.
