### ISSUE TITLE
Clarify "assign names from the pool of unused names"

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#25]
From Suzanne Woolf
https://www.ietf.org/mail-archive/web/dnsop/current/msg19170.html

Problems associated with Special-Use Domain Names

12. "assign names from the pool of unused names" is a little imprecise, should probably specify slightly further:

OLD:
   "Both ICANN and the IETF have the authority and formal processes to
   assign names from the pool of unused names..."

NEW:
   "Both ICANN and the IETF have the authority and formal processes to
   make new assignments from the pool of unassigned domain names, and expect names they add to
   be unique within the global namespace."

**Comment by rdroms** [comment]
I can understand the desire to be more precise about "pool of unused names".  I'm not sure the last phrase about uniqueness is entirely correct.  I'm not sure what the "global namespace" is and, for example, I wouldn't characterize locally-served zones as unique because of their local resolution context.

**Comment by Abhayakara** [comment]
I think what she's getting at is that any given name that can appear in the global namespace would be allocated not more than once.   It may be that it would be used in private ways that result in it having different meanings in different contexts, but in the global context it would have only one meaning.

**Comment by rdroms** [comment]
How about:

Both ICANN and the IETF have the authority and formal processes to
designate names from the pool of unassigned domain names as part of
the DNS Name System or as Special-Use Domain Names, respectively.  The
two organizations expect these designations to be unambiguous.

**Comment by Abhayakara** [comment]
That doesn't seem very clear to me.   You still aren't saying that they come out of the same namespace, and that's the point that's important to convey.

**Comment by rdroms** [comment]
Clearer?

    o  Both ICANN and the IETF have the authority and formal processes
      to assign Domain Names from the pool of unused names in the
      shared Domain Namespace, but no formal coordination process
      exists.  The lack of coordination complicates the management of
      the root of the Domain Namespace and may lead to conflicts in
      name assignments [SDO-ICANN-SAC090].

**Comment by Abhayakara** [comment]
Sure.

**Comment by wkumari** [comment]
WFM. I think some of the confusion is that there isn't really a pool of unused names -- that sounds like there are names which exits and are waiting to be used. Or, I've just solved Fermat's Last Theorem -- here are the letters I used "a-z" - just put them in the right order to see my solutiuon....

Possibly "Both ICANN and the IETF have the authority and formal processes to assign Domain Names from the  shared Domain Namespace" or "Both ICANN and the IETF have the authority and formal processes  to create and assign Domain Names from the set of all possible names in the
  shared Domain Namespace"?

**Comment by rdroms** [comment]
I like "Both ICANN and the IETF have the authority and formal processes to assign Domain Names from the shared Domain Namespace" ... concise and more accurate than "pool of unused names"

**Comment by rdroms** [comment]
Here's my complete suggested text:

o  Both ICANN and the IETF have the authority and formal processes to
   assign Domain Names from the shared Domain Namespace, but no formal
   coordination process exists.  The lack of coordination may allow
   conflicts in name assignments [SDO-ICANN-SAC090] and complicates the
   management of the root of the Domain Namespace.

**Comment by rdroms** [comment]
Merging in issue #26 

o  Both ICANN and the IETF have the authority and formal processes to
   assign Domain Names from the shared Domain Namespace, but no formal
   coordination process exists.  As names need to be unique, the lack of
   coordination to assure unambiguous assignment may allow conflicts in
   name assignments [SDO-ICANN-SAC090] and complicates the management of
   the root of the Domain Namespace.

**Comment by rdroms** [comment]
We should review issues #25, #26, #28, #39 as a package, as they all affect the same block of text.

**Comment by rdroms** [comment]
Resolved with issue #39
