### ISSUE TITLE
Explicitly call out "uniqueness constraint" as the problem with "lack of coordination"

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#26]
From Suzanne Woolf
https://www.ietf.org/mail-archive/web/dnsop/current/msg19170.html

Problems associated with Special-Use Domain Names

13. The "lack of coordination" is only a problem given the expectation that names created under multiple set of processes will be unique within a shared scope. This can be assumed in the definition of “domain name” or it can be explicitly called out here, but the uniqueness constraint has to be explicit somewhere, because without it there’s (arguably) no problem.

**Comment by rdroms** [comment]
Hm.  Add "to assure unambiguous designation":

      The lack of coordination to assure unambiguous designation complicates
      the management of the root of the Domain Namespace and may lead to
      conflicts in name assignments [SDO-ICANN-SAC090].

The original text seemed clear enough to me.

**Comment by Abhayakara** [comment]
ok

**Comment by wkumari** [comment]
That works for me, or we could more explicitly say "As names need to be unique, the lack of coordination to assure unambiguous designation ..". Either works for me...

**Comment by rdroms** [comment]
See issue #25

**Comment by rdroms** [comment]
We should review issues #25, #26, #28, #39 as a package, as they all affect the same block of text.

**Comment by rdroms** [comment]
Resolved with issue #39
