### ISSUE TITLE
Is "technical use" really ambiguous; too inclusive for some people and too limited for others

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#27]
From Suzanne Woolf
https://www.ietf.org/mail-archive/web/dnsop/current/msg19170.html

Problems associated with Special-Use Domain Names

14. You say: "The term "technical use" in RFC 2860 [RFC2860] is considered by
      some to be too inclusive."

Isn't the concern really that the term is ambiguous, so some people find it too inclusive and some people find it too limited? For instance, we've heard the view expressed that it wasn't intended to include names defined for non-DNS resolution mechanisms, so something like .onion or .local isn't covered; we've also seen it asserted that "technical use" by the IETF includes the ability to force a change to the DNS root zone by ICANN. (As a personal view, I don't support either extreme.)

**Comment by rdroms** [comment]
In the interest of inclusivity (I don't think I've seen an assertion like the one Suz mentions), we could expand the text in question to:

      The interpretation of the term "technical use" from RFC 2860
      [RFC2860], as used in the development of RFC 6761 and the
      designation of SUDNs, is considered by some to be too inclusive
      and by others to be too limited.

**Comment by Abhayakara** [comment]
How about:

The meaning of the term "technical use" in RFC 2860 is never explained in detail.   RFC 6761 represents one possible interpretation.   Although this interpretation represents the current IETF consensus, there are participants consider it to be too broad, and also participants who consider it to be too narrow.

What I want to get at is that it's not the case that everybody disagrees with the interpretation chosen in RFC 6761.

**Comment by rdroms** [comment]
Excellent; absolutely WFM.

**Comment by wkumari** [comment]
And me...

**Comment by rdroms** [comment]
Text updated:

OLD:

   o  The term "technical use" in RFC 2860 [RFC2860] is considered by
      some to be too inclusive.

NEW:

   o  The term "technical use" in RFC 2860 [RFC2860] is never explained
      in detail.  RFC 6761 represents one possible interpretation.
      Although this interpretation represents the current IETF
      consensus, there are participants consider it to be too broad, and
      also participants who consider it to be too narrow.
