### ISSUE TITLE
Clarify meaning of ""The IETF and ICANN each have administrative authority over the  Domain Namespace." (3 issues)

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#28]
From Suzanne Woolf
https://www.ietf.org/mail-archive/web/dnsop/current/msg19170.html

Problems associated with Special-Use Domain Names

15. You say "The IETF and ICANN each have administrative authority over the
      Domain Namespace.  Not all developers of protocols on the internet
      agree that this authority should reside with the IETF and ICANN."

It almost makes more sense to me to say the IETF and ICANN each have an ability to add names to the domain name space under conditions such that people will use them, but there's no shared view of what that means in terms of the shared global namespace. Specifically, there's no shared view of how to avoid collisions such that the uniqueness constraint that people expect of their domain names will be reliably honored.

16. Same comments on the text "Although IETF and ICANN nominally have authority
      over this namespace, neither organization can enforce that authority over any
      third party who wants to just start using a subset of the namespace."

17. More generally, on the last two comments, the use of the word "authority" may need to be clarified here. It sounds obvious, but I think if it really were obvious we wouldn't need to think about this stuff quite so hard. If we assume RFC 2860 is not open for modification (one of our ground rules from early on) and it's not the WG's job to interpret it, we're left with the practical reality that ICANN has operational authority over the DNS root zone under its community's processes, the IETF has operational authority over the SUDN registry under its processes (RFC 6761).

**Comment by rdroms** [comment]
I disagree with Suz's interpretation of the text in the first issue; I think it means that some developers think that all authority over the Domain Namespace should reside jointly in the IETF and ICANN.  If I have that right, then some edits are needed for clarification.

If I've interpreted the text in the first issue correctly, I don't think any changes are needed in the original text in the second issue.

I don't really understand the third issue.

**Comment by Abhayakara** [comment]
The text she's referring to actually says the opposite: that there are people with a legitimate stake in this question who believe that _neither_ the IETF _nor_ ICANN should have authority over this.   That is the point being made there.

**Comment by rdroms** [comment]
I actually meant to write what you explained; I seem to have missed a critical "not".  In any event I agree with you.

**Comment by wkumari** [comment]
SGTM.

**Comment by rdroms** [comment]
This issue needs to be considered in conjunction with issue #39

**Comment by rdroms** [comment]
We should review issues #25, #26, #28, #39 as a package, as they all affect the same block of text.

**Comment by rdroms** [comment]
Resolve with issue #39
