### ISSUE TITLE
Add a reason to bypass external process: expectation for use of new name to be restricted to local scope

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#29]
From Suzanne Woolf
https://www.ietf.org/mail-archive/web/dnsop/current/msg19170.html

Problems associated with Special-Use Domain Names

19. I'd add to the list of possible reasons for putting a name into use without following any external process: "Names are expected to be resolved only within the local scope for a protocol or network, or by some non-DNS protocol, and designers don't realize or don't care that modern systems and applications may nonetheless try to resolve domain names with no context signaling in the global DNS." Handwaving about authority aside, the real concern in these cases is interoperability; no one would care if such names didn't tend to leak, but leaking is an interoperability problem.

**Comment by rdroms** [comment]
How about:

      *  Unaware that using a name with the expectation that it will
         only be used within some local context, for example in an
         experimental or locally scoped usage, may be resolved
         through the Global DNS by some applications; leakage of these
         names may cause local and global operational problems.

**Comment by Abhayakara** [comment]
That's too much.   How about:

* Unaware that a name intended to be used only locally may nevertheless leak

* Unaware that a name used locally with informal allocation may subsequently be allocated formally, creating operational problems

**Comment by rdroms** [comment]
WFM

**Comment by wkumari** [comment]
... and for me.

**Comment by rdroms** [comment]
Updated text:

OLD:

   o  Organizations do in fact sometimes commandeer subsets of the
      namespace.  Reasons a third party might do this include:

      *  Unaware that a process exists for assigning such names

      *  Intended use is covered by gTLD process, but no gTLD process is
         ongoing

      *  Intended use is covered by gTLD process, don't want to pay fee

      *  Intended use is covered by some IETF process, but don't want to
         follow process

      *  Intended use is covered by ICANN or IETF process, but expected
         outcome is refusal or non-action

NEW:

   o  Organizations do in fact sometimes use subsets of the Domain
      Namespace without following established processes.  Reasons a
      third party might do this include:

      *  Unaware that a process exists for assigning such names

      *  Intended use is covered by gTLD process, but no gTLD process is
         ongoing

      *  Intended use is covered by gTLD process, don't want to pay fee

      *  Intended use is covered by some IETF process, but don't want to
         follow process

      *  Intended use is covered by ICANN or IETF process, but expected
         outcome is refusal or non-action

      *  Unaware that a name intended to be used only locally may
         nevertheless leak

      *  Unaware that a name used locally with informal allocation may
         subsequently be allocated formally, creating operational
         problems
