### ISSUE TITLE
Conrad: Observation: ICANN doesn't have change control on ccTLDs

### ISSUE THREAD

**Issue by Abhayakara** [Abhayakara/draft-tldr-sutld-ps#3]
ICANN already cedes change control of some subsets of the top-level namespace to other organizations, e.g. ISO for ccTLDs

PRACTICE: refer to ICANN practice WRT ccTLDs

SEC CONS: Bortzmeyer points out that having resolvers look stuff up in the DNS and take protocol actions based on the response is RISKy.

Jaeggli:

PRACTICE: https://gnso.icann.org/mailing-lists/archives/council/msg16659.html

Woolf:

PRACTICE: use https://datatracker.ietf.org/liaison/1351/ instead

subsequently:

Please do not get into “institutional arrangements.”   That is solution space, not problem space.

subsequently:

Durand:

That is certainly your right to read it that way, but it is not what the authors are saying, or at least not what they intended to say.   What draft-adpkja-dnsop-special-names-problem is doing is explaining that all names are subject to socio-economic pressures, and ICANN has had to develop a complex process to evaluate those pressures and deal with them. That process may not be perfect, but it exists.  ETF has no such process in place.

Woolf:

It is a matter of scope, to say nothing of opinion, that “all names are subject to socio-economic pressures.” There are a great many identifiers in use on the internet, and it’s hard to even evaluate this claim without some discussion of context. (We spent much of the ARCING BOF on pretty much this point.)

Given that discussion of “special use names” is even more likely than most to suffer from assumptions about context, a more precise formulation of this claim would probably be helpful.

```
Conrad:
```

The way I see it, "Internet names" (that is, domain names whether they are used in the DNS or not) are typically used to identify hosts, end points, or services on the Internet. People tend to get wound up with their identity and how that identity is made available on the Internet (or overlays on top of the Internet). That being wound up often result in socio-economic pressures, e.g., being bought/sold, triggering lawsuits over ownership/existence, etc.  Do some of those identities not get tied up in those socio-economic pressures?  Sure, the vast majority.  However, I'm not sure I can see how all identities are not subject to socio-economic pressures.

[Not sure what my action item is here.   XXX]

**Comment by wkumari** [comment]
Me neither. However, it might be worth just mentioning in the document that there is another organization which often gets forgotten who has access to the namespace, and that's ISO 3166. 

(This is somewhat of a copout, because I couldn't figure out the action item either. Perhaps there isn't one.)

**Comment by wkumari** [comment]
Yup. Please see issue #22 
Updating to reference the DAG.

**Comment by rdroms** [comment]
Warren - please explain "Updating to reference the DAG."  Are there changes in the doc from this issue?
