### ISSUE TITLE
Add justification for concern about IETF's ability to assign names for technical use

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#31]
From Suzanne Woolf
https://www.ietf.org/mail-archive/web/dnsop/current/msg19170.html

Problems associated with Special-Use Domain Names

21. The text "If there were no process for assigning names for technical use
      through the IETF, there is a concern that protocols that require
      such names would not be able to get them." seems a little incomplete to me.

I would add something like "This view is usually justified by the observation that the IETF has never asserted control or authority over what protocols are 'allowed' on the internet, and that the principle of 'permissionless innovation' suggests there should be a way for people to include new uses of domain names in new protocols and applications." After all, we don't ask people to prove their application is "good" before we "let" them use TCP for it, even though we're the SDO for TCP. (I'm not personally sure this is a good analogy, but I've heard it. There are plenty of protocol parameter registries for which the policy is "just ask" or FCFS or expert review, so I think this is really a question about registry policy.)

**Comment by rdroms** [comment]
Suz's point doesn't match up with the text in question for me.  I read the original text to mean that if the IETF can't designate names for special use in ways outside those for which ICANN can designate (i.e., just DNS resolution through root zone context), there would be no way to operate new protocols that share the Domain Namespace with the Global DNS.  I read her point to be that there is no sandbox in which a name can be used without permission from either IETF or ICANN.

But, I may be confused...

...and there is nothing about the issue of no experimental sandbox - which the alt-tad draft is addressing.  My suggestion is to leave the original text and add a new bullet problem:

   o  There is no provision for Domain Names that can be used for
      experimentation or similar purposes without going through a
      formal designation process.

**Comment by Abhayakara** [comment]
Hm, do we not already make that point?   If not, sure.

**Comment by Abhayakara** [comment]
- Although IETF and ICANN nominally have authority over this namespace, neither organization can enforce that authority over any third party who wants to just start using a subset of the namespace.   Such parties may observe that the IETF has never asserted control or authority over what protocols are 'allowed' on the internet, and that the principle of 'permissionless innovation' suggests there should be a way for people to include new uses of domain names in new protocols and applications.

**Comment by rdroms** [comment]
Consensus to make change to related bullet and leave originally cited text unchanged.

**Comment by rdroms** [comment]
Edits complete
