### ISSUE TITLE
Have assignments through RFC 6761 really had "technical mistakes"?

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#32]
From Suzanne Woolf
https://www.ietf.org/mail-archive/web/dnsop/current/msg19170.html

Problems associated with Special-Use Domain Names

22. You say "In cases where the IETF has made assignments through the RFC 6761 process, technical mistakes have been made," but I admit I'm having trouble identifying an example of an addition to the registry that included such technical mistakes. This text almost sounds like it meant "In cases where the IETF has *not* made assignments through the RFC 6761 process...."

**Comment by rdroms** [comment]
My recollection is that Stuart has pointed out issues with the ipv4only and onion designations.  So, I think we should retain the text in question.  However, I suggest a little word-smithing to clarify that the problem also includes cases in which de facto designation of SUDNs has occurred without following the RFC 6761 process at all:

   o  In cases where the IETF has made assignments through the RFC 6761
      process, technical mistakes have been made due either to
      misunderstandings as to the actual process that RFC 6761 specifies
      (e.g., treating the list of suggested considerations for assigning
      a name as a set of requirements all of which must be met).  In
      other cases, the IETF has made de facto assignments of SUDNs
      without following the RFC 6761 process.

**Comment by Abhayakara** [comment]
wfm

**Comment by wkumari** [comment]
+1

**Comment by rdroms** [comment]
Updated text

OLD:

   o  In cases where the IETF has made assignments through the RFC 6761
      process, technical mistakes have been made due either to
      misunderstandings as to the actual process that RFC 6761 specifies
      (e.g., treating the list of suggested considerations for assigning
      a name as a set of requirements all of which must be met), or to a
      failure to follow the process that was defined in RFC 6761.

NEW:

   o  In some cases where the IETF has made assignments through the RFC
      6761 process, technical mistakes have been made due to
      misunderstandings as to the actual process that RFC 6761 specifies
      (e.g., treating the list of suggested considerations for assigning
      a name as a set of requirements all of which must be met).  In
      other cases, the IETF has made de facto assignments of SUDNs
      without following the RFC 6761 process.
