### ISSUE TITLE
Clarify paragraph that begins "There are several Domain Name TLDs that have been commandeered [...]"

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#33]
From Suzanne Woolf
https://www.ietf.org/mail-archive/web/dnsop/current/msg19170.html

Problems associated with Special-Use Domain Names

24. The next para, which begins "There are several Domain Name TLDs that have been commandeered without due process for a variety of purposes [SDO-ICANN-COLL]. The status of these names need to be clarified...." puzzles me. Could you clarify why it's not redundant with the previous case? You cite the same draft for both, but I think you're trying to make different points ("unsafe to assign" vs. "commandeered"-- are they the same thing? Has anyone brought up different risks associated with them?)

**Comment by rdroms** [comment]
Also see #41 

Just reading the two issues in question quickly, they seem to be different, but out of order.  That is, the second issue is a statement of a general problem in the lack of documentation of commandeered names, and the first issue is a specific way in which those commandeered names could be document, but failed in practice.  I suggest just swapping the two issues without changing any text:

   o  There are several Domain Name TLDs that have been commandeered
      without due process for a variety of purposes [SDO-ICANN-COLL].
      The status of these names need to be clarified and recorded to
      avoid future disputes about their use. [ Ed note: We note that
      DNSOP has previously discussed some of these in draft-chapin-
      additional-reserved-tlds-02, and decided not to adopt the draft -
      https://www.ietf.org/mail-archive/web/dnsop/current/msg14887.html
      .  The authors are not recommending that DNSOP revisit this,
      rather that is needs to be addressed in some venue. ]

   o  In principle, the RFC 6761 process could be used to document the
      existence of Domain Names that are not safe to assign, and provide
      information on how those names are used in practice.  However,
      attempts to use RFC6761 to accomplish this
      [I-D.chapin-additional-reserved-tlds] have not been successful.
      One side effect of this is that any mitigation effect on the root
      name servers has been missed.

**Comment by wkumari** [comment]
I *think* that that works, but am not sure. If it still seems redundant / confusing we could collapse the bullets into one...

**Comment by rdroms** [comment]
I see I've suggested two rewrites of these paragraphs.  Check out issue #41 as well.  I like the rewrite in #41 better.

**Comment by rdroms** [comment]
Confirming - see issue #41  for final text to address issues #11, #41 and #33

**Comment by Abhayakara** [comment]
Closed as addressed by #41
