### ISSUE TITLE
Separate two problems in paragraph that begins "No mechanism exists for adding a name to the registry...." (2 issues)

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#34]
From Suzanne Woolf
https://www.ietf.org/mail-archive/web/dnsop/current/msg19170.html

Problems associated with Special-Use Domain Names

25. The para that begins "No mechanism exists for adding a name to the registry...." is talking about two different problems (IETF is responsible, no precedence for assignment). It might be clearer if you separate them.

26. There's also a third point that there's no precedence for resolution, either; there's no mechanism in the registry for specifying which protocol is expected for resolution, so no precedence between the functional default (DNS) and others. SO for instance, the registry won't tell people that the string ".onion" when it appears in their networks in domain name contexts, is supposed to be resolved by an entirely different protocol. This may be a problem with the registry structure rather than its existence or its contents, and it may not be the only one (early versions of draft-adpkja-dnsop-special-names-problem had some discussion of the registry itself IIRC).

**Comment by rdroms** [comment]
I get the first two points, and sort of agree.  Roughly, I think the two points are:

o The only mechanism for assigning a special-use name that does not use DNS for resolution through the global root zone context is to claim that the IETF is responsible for the name and is using it for "technical use".

o There is no formal agreement that a name assigned by the IETF for "technical use" or by ICANN for use in the global DNS can't be also assigned by the other organization, causing a conflict in the use of that name.

However, I don't totally agree with the third point.  I think the registry is pretty clear about how to solve special-use names through the information required by RFC 6761 (at least in theory).  There is the underlying problem that names don't include metadata that specify the resolution protocol and context for that name, but I think we've discussed that problem elsewhere.

**Comment by Abhayakara** [comment]
I would add a third bullet item:
- There is no explicit scoping as to what can constitute a "technical use" and what cannot, and there is also no consensus within the IETF as to what this term means.

**Comment by Abhayakara** [comment]
The first bullet item in Ralph's comment above and the bullet item I just added would replace this bullet item on page four of the current doc:

- The term "technical use" in RFC 2860 [RFC2860] is considered by some to be too inclusive.

**Comment by Abhayakara** [comment]
We have consensus on this, and should retain reference to 2860.

**Comment by rdroms** [comment]
Issue needs review...  The bullet we agreed to replace now reads, after edits:

          The term "technical use" in <xref target="RFC2860">RFC
          2860</xref> is never explained in detail. RFC 6761
	  represents one possible interpretation. Although this
	  interpretation represents the current IETF consensus, there
	  are participants consider it to be too broad, and also
	  participants who consider it to be too narrow

The meaning of this text is somewhat different from the proposed:

     There is no explicit scoping as to what can constitute a "technical use" and what cannot,
     and there is also no consensus within the IETF as to what this term means.

After rereading both bits of text, I find I prefer the former.  I disagree that "there is also no consensus within the IETF as to what this term means" - there are some who disagree, but I think there is consensus.

**Comment by Abhayakara** [comment]
Okay, if you think there's a consensus, can you say what the consensus is and where it is documented?   ;)

**Comment by rdroms** [comment]
Well...according to the text we added from issue #27, current IETF consensus is documented in RFC 6761.

**Comment by Abhayakara** [comment]
Hm, okay, I remember that conversation, but 6761 never uses the term "technical use."

**Comment by rdroms** [comment]
Seems to me this discussion has overlapped with issue #27; resolution of issue #27 has already changed some of the text under discussion here.  My suggested text (updating the previous change from issue #27) is:

CURRENT:

   o  No mechanism exists for adding a name to the registry without
      claiming that the IETF is responsible for that name, nor is it
      possible to state a precedence for the name, e.g., "if ICANN
      delegates this name, ICANN's delegation takes precedence."

NEW:

o The only mechanism for assigning a special-use name that does not use DNS for resolution through the global root zone context is to claim that the IETF is responsible for the name and is using it for "technical use".

CURRENT:

   o  The term "technical use" in RFC 2860 [RFC2860] is never explained
      in detail.  RFC 6761 represents one possible interpretation.
      Although this interpretation represents the current IETF
      consensus, there are participants consider it to be too broad, and
      also participants who consider it to be too narrow.

NEW:

o  There is no explicit scoping as to what can constitute a "technical use" and what cannot,
 and there is also no consensus within the IETF as to what this term means.

**Comment by Abhayakara** [comment]
Er, no, remember that the point of that first bullet item is to talk about the problem that the IETF can't make an observation about a name being in use and put that name in the IETF registry without becoming the owner of that name, and being subject to, e.g., lawsuits if there is a dispute about the name.

**Comment by rdroms** [comment]
Now I'm confused ... In my mind, the first "CURRENT/NEW" text substitution addresses the issue that the only way to get a name in the special use registry is for the IETF to own it and claim it for "technical use".

**Comment by Abhayakara** [comment]
Yes, and yet when I re-read the text, _I_ failed to understand its meaning.   How about this:

* The only mechanism for assigning a special-use name that does not use DNS for resolution through the global root zone context is to add it to the IETF special-use names registry; however, there is no way to add a name to that registry without saying that the IETF is responsible for the name and is using it for a "technical use".

**Comment by rdroms** [comment]
LGTM ...so , now we have:

CURRENT:

o No mechanism exists for adding a name to the registry without
claiming that the IETF is responsible for that name, nor is it
possible to state a precedence for the name, e.g., "if ICANN
delegates this name, ICANN's delegation takes precedence."

NEW:

o The only mechanism for assigning a special-use name that does not use DNS for resolution through the global root zone context is to add it to the IETF special-use names registry; however, there is no way to add a name to that registry without saying that the IETF is responsible for the name and is using it for a "technical use".

CURRENT:

o The term "technical use" in RFC 2860 [RFC2860] is never explained
in detail. RFC 6761 represents one possible interpretation.
Although this interpretation represents the current IETF
consensus, there are participants consider it to be too broad, and
also participants who consider it to be too narrow.

NEW:

o There is no explicit scoping as to what can constitute a "technical use" and what cannot,
and there is also no consensus within the IETF as to what this term means.

Warren - OK with you?

**Comment by Abhayakara** [comment]
Blrg.   Now that's a real run-on sentence.   How about:

* There are two mechanisms for assigning names: either a name can be placed in the DNS zone(s) where it is appropriate, or it can be listed in the IETF Special-Use Names registry, or both.   For names that will not appear in the DNS, registering them in the IETF registry carries with it an implication that the name has been allocated by the IETF.   In some cases, it may be desirable to place a name in the registry in order because it is known to be in common use, but is not in use by either the IETF or through ICANN.   There is no way to indicate in the registry that a name has been allocated on this basis.

**Comment by rdroms** [comment]
I think that text overlooks some important specifics.  Suggestion:

* A Domain Name can be identified as either a DNS name by placing it in the DNS zone(s) or as a Special Use Domain Name by adding it to the IANA registry.  Some names are in both places; for example, some locally served zone names are in DNS zones and documented in the Special Use Domain Names registry.  At present, the only way a Domain Name can be added to the Special Use Domain Name registry is for the IETF to take responsibility for the name and designate it for "technical use".  There are other potential uses for Domain Names that should be recorded in the registry, but for which the IETF should not take responsibility.

**Comment by Abhayakara** [comment]
Yes, that's perfect.   Thanks.

**Comment by rdroms** [comment]
Edits made.
