### ISSUE TITLE
Clarify "No process exists [...]" to include both IETF process and other process

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#35]
From Suzanne Woolf
https://www.ietf.org/mail-archive/web/dnsop/current/msg19170.html

Problems associated with Special-Use Domain Names

27. The text "No process exists for checking documents to make sure they don't accidentally assign names (e.g.  RFC 7788)." could be taken to mean either that the IETF has no such process (and it's true, we don't) or that no one else does either (which is also true). Within the IETF, this breaks the standards process; on the wider scale, it risks collision between the same string being assigned informally to multiple, potentially colliding uses (the folks who wanted to use .home in homenets, and the folks already using .home for something else), with no certainty they won't collide and no rule for determining which use, if either, is an error.

**Comment by Abhayakara** [comment]
OLD:
- No process exists for checking documents to make sure they don't  accidentally assign names (e.g.  RFC 7788).

NEW:
- There is no formal mechanism that ensures that we check to make sure that a document being considered for publication does not unintentionally violate the IETF process for adding special use names to the registry (e.g.  RFC 7788).

**Comment by Abhayakara** [comment]
We have consensus to make this change.

**Comment by rdroms** [comment]
Edits made
