### ISSUE TITLE
Expand on desire for special-use names to be human-readable

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#36]
From Suzanne Woolf
https://www.ietf.org/mail-archive/web/dnsop/current/msg19170.html

Problems associated with Special-Use Domain Names

28. The text “It is generally assumed that protocols that need a special-use name need a human-readable special-use name. This assumption may not be warranted in all cases.” doesn’t go far enough. People assume both that they need a human-readable name, and that they need a single label name (“TLD”). Both assumptions, especially together, create a perception that there’s a limited number of useful domain names in the world, with corresponding tendencies to treat the underlying resource as scarce. Domain names aren’t scarce; domain names that meet some of the implicit assumptions people make about them might well be.

**Comment by rdroms** [comment]
OLD:

   o  It is generally assumed that protocols that need a special-use
      name need a human-readable special-use name.  This assumption may
      not be warranted in all cases.

NEW:

   o  It is generally assumed that protocols that need a special-use
      name need a mnemonic, single-label, human-readable special-use
      name. This assumption may not be warranted in all cases.

**Comment by wkumari** [comment]
Perhaps we should add in something about *why* some people want many of them to be human readable / typable?

Also, there are 2.8e+12 possible 8 letter TLDs, so even if people make the assumptions we still have, er, lots...

**Comment by rdroms** [comment]
And, I suppose, why the assumption may not be warranted.

**Comment by rdroms** [comment]
Updated suggested fix:

OLD:

o It is generally assumed that protocols that need a special-use
name need a human-readable special-use name. This assumption may
not be warranted in all cases.

NEW:

o It is generally assumed that protocols that need a special-use
name need a mnemonic, single-label, human-readable special-use
name, for use in user interfaces such as command lines or URL
entry fields. This assumption may not be warranted in all cases;
for example, in applications where the DNS name is never visible
to a user.

**Comment by Abhayakara** [comment]
How about "while this assumption is likely correct in some cases, it is likely not correct in all cases, ..."

**Comment by Abhayakara** [comment]
we have consensus

**Comment by rdroms** [comment]
Edits completed
