### ISSUE TITLE
 Will I-D.lewis-domain-names be published as an Informational RFC?

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#38]
From Russ Housley:

https://www.ietf.org/mail-archive/web/dnsop/current/msg19239.html

Will I-D.lewis-domain-names be published as an Informational RFC as well?  If not, then the Introduction needs to extract highlights from that document.

**Comment by rdroms** [comment]
I expect that I-D.lewis-domain-names be published as an Informational RFC.  Nothing to change in response to this issue.

**Comment by Abhayakara** [comment]
consensus not to change

**Comment by rdroms** [comment]
No changes needed; issue closed
