### ISSUE TITLE
Overlapping bullets in Section 3, with proposed restructuring

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#39]
From Russ Housley:
https://www.ietf.org/mail-archive/web/dnsop/current/msg19239.html

These three bullets in Section 3 overlap:

   o  Both ICANN and the IETF have the authority and formal processes to
      assign names from the pool of unused names, but no formal
      coordination process exists.  The lack of coordination complicates
      the management of the root of the Domain Namespace and may lead to
      conflicts in name assignments [SDO-ICANN-SAC090].

   o  The IETF and ICANN each have administrative authority over the
      Domain Namespace.  Not all developers of protocols on the internet
      agree that this authority should reside with the IETF and ICANN.

   o  Although IETF and ICANN nominally have authority over this
      namespace, neither organization can enforce that authority over
      any third party who wants to just start using a subset of the
      namespace.

I think there is one main point and two observations.  The main point is that both ICANN and the IETF have the authority and formal processes to assign previously unused names.  The first observation is that ICANN and the IETF need to coordinate to avoid conflicts.  The second observation is that some think that the authority is misplaced.  The second observation needs to be expanded to state the consequence, which I assume is squatting.  If I guessed correctly, the text should explain that squatting leads to conflicts.  The third observation is that neither ICANN nor the IETF has any technical means to prevent squatting.

**Comment by rdroms** [comment]
This issue is related to #28

**Comment by rdroms** [comment]
I see we had a similar situation in #22 ,  in which the list item actually contains both some background material and problems that then derive from that problem.  In this case, I agree with Russ that the IETF and ICANN each have authority over some parts of the Domain Namespace, and that the union of their respective authorities cover the entire Domain Namespace (as derived from RFC 2860). 

One way to resolve the issue would be to move the background to a point earlier in the document, and then extract out the problems from the current rev of sutld-ps, and as Russ and Suz (in issue #28 ) refined them. 

On the other hand, the document already contains a background section on RFC 2860, which could reasonably be extended to be explicit about the relationship between IETF and ICANN authority and processes over the Domain Namespace, with a forward pointer from the appropriate problems to that background...

I'll try the latter approach.

Strawperson text:

o No formal coordination process exists between the name assignment
processes in the IETF and ICANN (see section 4.1.3). The lack of
coordination complicates the management of the root of the Domain
Namespace and may lead to conflicts in name assignments
[SDO-ICANN-SAC090].

o Not all developers of protocols on the internet agree that authority
over the entire Domain Namespace should reside solely with the IETF
and ICANN.

o Neither the IETF nor ICANN can enforce their authority over the
Domain Namespace to prevent any third party who wants to just start
using a subset of the namespace.  Uncoordinated use of parts of the
Domain Namespace by third parties can lead to conflicts in the usage
of Domain Names and failures in Domain Name resolution.

Add to section 4.1.3:

Implicit in the MoU is the fact that the IETF and ICANN retain,
between them, sole authority for assigning any names from the Domain
Namespace.  Both the IETF and ICANN have internal processes for making
such assignments.

**Comment by wkumari** [comment]
I'm fine with the strawman (thanks!)
I suspect that someone somewhere will claim that ICANN *can* assert their authority by refusing to delegate a new TLD (if one limits "their authority" / remit to the DNS root), but that would be a reach :-P

**Comment by rdroms** [comment]
We should review issues #25, #26, #28, #39 as a package, as they all affect the same block of text.

**Comment by rdroms** [comment]
Hm.  Third bullet, above, was just modified with an earlier edit today.  The newly added text doesn't seem to capture the idea that "Uncoordinated use of parts of the
Domain Namespace by third parties can lead to conflicts in the usage
of Domain Names and failures in Domain Name resolution."

That last sentence now appears in the first bullet as:

	  The lack of coordination complicates the management of
	  the root of the Domain Namespace and <xref
	  target="SDO-ICANN-SAC090"> may lead to conflicts in name
	  assignments </xref>

I'm going to go ahead and close this issue.  Let me know if you disagree.
