### ISSUE TITLE
Problem: this isn't just about special-use TLDs

### ISSUE THREAD

**Issue by Abhayakara** [Abhayakara/draft-tldr-sutld-ps#4]
PROBLEM: add a terminology section, make distinction between TLDs, which are delegated in the DNS such that names under them can be resolved using DNS recursion, and SUTLNs? which are not.   SUTLD->SUTLN

Actually, this document is really about the special use name problem; special-use top-level names are a subset of that problem.

**Comment by wkumari** [comment]
Addressed.

**Comment by rdroms** [comment]
Warren - please explain how this issue was addressed?  Are there changes in the doc from this issue?
