### ISSUE TITLE
Note that time to publish spec for .local included inventing SUDN registry

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#40]
From Russ Housley:
https://www.ietf.org/mail-archive/web/dnsop/current/msg19239.html

I think that the Section 3 bullet on .local should explain that the amount of time involved was excessive, but part of the reason was that the process for special-use assignments was being invented.  As a result, .onion took much less time.

**Comment by rdroms** [comment]
OLD:

   o  The RFC6761 process is sufficiently uncertain that some protocol
      developers have assumed they could not get a name assigned; the
      process of assigning the first new name ('.local') using the RFC
      6761 process took more than ten years from beginning to end:
      longer by a factor of ten than any other part of the protocol
      development process.  Other uses of the process have proceeded
      more smoothly, but there is a reasonably justified perception that
      using this process is likely to be slow and difficult, with an
      uncertain outcome.

NEW:

   o  The RFC6761 process is sufficiently uncertain that some protocol
      developers have assumed they could not get a name assigned; the
      process of assigning the first new name ('.local') using the RFC
      6761 process took more than ten years from beginning to end:
      longer by a factor of ten than any other part of the protocol
      development process (to be fair, that ten years included time to
      develop the process as well as use it).  Other uses of the process
      have proceeded more smoothly, but there is a reasonably justified
      perception that using this process is likely to be slow and
      difficult, with an uncertain outcome.

**Comment by wkumari** [comment]
I'm fine with this. 
I slightly prefer: 
"(largely because this ten years included...)" - "to be fair" sounds grudging...

**Comment by rdroms** [comment]
Warren - I agree with your editorial suggestion.

**Comment by Abhayakara** [comment]
consensus

**Comment by rdroms** [comment]
edits completed
