### ISSUE TITLE
Reword bullet in Section 3 regarding Domain Name TLDs that have been commandeered, as reported in SDO-ICANN-COLL

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#41]
From Russ Housley:
https://www.ietf.org/mail-archive/web/dnsop/current/msg19239.html

I think that the Section 3  bullet that references https://www.ietf.org/mail-archive/web/dnsop/current/msg14887.html should be reworded.  The information in the Ed Note probably does not belong in the Informational RFC.

**Comment by rdroms** [comment]
See also #33 

I think a pointer to the discussion of issues that went along with consideration of chapin-additional-reserved-tlds is useful.  If we think the text ought to be changed, how about:

   o  There are several Domain Name TLDs that have been commandeered
      without due process for a variety of purposes [SDO-ICANN-COLL].
      The status of these names need to be clarified and recorded to
      avoid future disputes about their use.

   o  In principle, the RFC 6761 process could be used to document the
      existence of Domain Names that are not safe to assign, and
      provide information on how those names are used in practice.
      However, attempts to use RFC6761 to accomplish this
      documentation [I-D.chapin-additional-reserved-tlds] have not
      been successful.  One side effect of the lack of formal
      agreement on this documentation is that any mitigation effect on
      the root name servers has been missed. Discussion of the issues
      related to these names, which accompanied the consideration of
      chapin-additional-reserved-tlds, may provide useful input to
      future work on solutions.  That discussion begins at:
      https://www.ietf.org/mail-archive/web/dnsop/current/msg14887.html

**Comment by wkumari** [comment]
I like the new text - minor nit is that the second chapin-additional-reserved-tlds should also be a reference (obviously).

**Comment by rdroms** [comment]
Here's the current state of the relevant text (after resolution of some [not all] relevant issues):

OLD:

   o  In principle, the RFC 6761 process could be used to document the
      existence of Domain Names that are not safe to assign, and provide
      information on how those names are used in practice.  However,
      attempts to use RFC6761 to accomplish this
      [I-D.chapin-additional-reserved-tlds] have not been successful.
      One side effect of this is that any mitigation effect on the root
      name servers or on privacy considerations has been missed.

   o  There are several Domain Name TLDs that are in use without due
      process for a variety of purposes [SDO-ICANN-COLL].  The status of
      these names need to be clarified and recorded to avoid future
      disputes about their use. [ Ed note: We note that DNSOP has
      previously discussed some of these in draft-chapin-additional-
      reserved-tlds-02, and decided not to adopt the draft -
      https://www.ietf.org/mail-archive/web/dnsop/current/msg14887.html
      .  The authors are not recommending that DNSOP revisit this,
      rather that is needs to be addressed in some venue. ]

I suggest:

NEW:

o There are several Domain Name TLDs that are in use
without due process for a variety of purposes [SDO-ICANN-COLL].
The status of these names need to be clarified and recorded to
avoid future disputes about their use.

  o  In principle, the RFC 6761 process could be used to document the
      existence of Domain Names that are not safe to assign, and provide
      information on how those names are used in practice.  However,
      attempts to use RFC6761 to accomplish this documentation
      have not been successful (for example, see "Additional Reserved
      Top Level Domains", [I-D.chapin-additional-reserved-tlds]).
      One side effect of this is that any mitigation effect on the root
      name servers or on privacy considerations has been missed.
      Discussion of the issues
      related to these names, which accompanied the consideration of
      "Additional Reserved Top Level Domains", may provide useful input to
      future work on solutions. That discussion begins at:
      https://www.ietf.org/mail-archive/web/dnsop/current/msg14887.html

Note that resolving this issue also resolves issues #33 and #11 .

**Comment by rdroms** [comment]
OLD:

o In principle, the RFC 6761 process could be used to document the
existence of Domain Names that are not safe to assign, and provide
information on how those names are used in practice. However,
attempts to use RFC6761 to accomplish this
[I-D.chapin-additional-reserved-tlds] have not been successful.
One side effect of this is that any mitigation effect on the root
name servers or on privacy considerations has been missed.

o There are several Domain Name TLDs that are in use without due
process for a variety of purposes [SDO-ICANN-COLL]. The status of
these names need to be clarified and recorded to avoid future
disputes about their use. [ Ed note: We note that DNSOP has
previously discussed some of these in draft-chapin-additional-
reserved-tlds-02, and decided not to adopt the draft -
https://www.ietf.org/mail-archive/web/dnsop/current/msg14887.html
. The authors are not recommending that DNSOP revisit this,
rather that is needs to be addressed in some venue. ]

NEW:

o There are several Domain Name TLDs that are in use
without due process for a variety of purposes [SDO-ICANN-COLL].
The status of these names need to be clarified and recorded to
avoid future disputes about their use.

o In principle, the RFC 6761 process could be used to document the
existence of Domain Names that are not safe to assign, and provide
information on how those names are used in practice. However,
attempts to use RFC6761 to accomplish this documentation
have not been successful (for example, see "Additional Reserved
Top Level Domains", [I-D.chapin-additional-reserved-tlds]).
One side effect of this is that any mitigation effect on the root
name servers or on privacy considerations has been missed.

**Comment by rdroms** [comment]
Consensus to use this text to resolve #11, #33 and #41

**Comment by rdroms** [comment]
Edits completed
