### ISSUE TITLE
Spell out SUDN and SUTLDN rather than use acronyms

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#43]
From Russ Housley:
https://www.ietf.org/mail-archive/web/dnsop/current/msg19239.html

The “SUDN” and “SUTLDN” acronyms are defined, but they are not used very often.  I wonder is spelling it out in every case would be more clear.

**Comment by rdroms** [comment]
We ought to have consistency in usage and capitalization.   SUDN and SUTLDN each occur about 5 times in the doc.  Probably easier to read if we just spell SUDN and SUTLDN out everywhere and eliminate the definitions from "Terminology".

Doc should also be more consistent with capitalization and usage: "special-use Domain Name" or "Special-Use Domain Name" or "special-use name"

**Comment by wkumari** [comment]
SGTM.

**Comment by Abhayakara** [comment]
consensus to spell it out.   consensus to capitalize as in second-to-last example.

**Comment by rdroms** [comment]
Use "Special-Use Domain Name" and "Special-Use Top Level Domain Name" as appropriate throughout.

**Comment by rdroms** [comment]
Edits completed
