### ISSUE TITLE
4.3 should be made more prominent

### ISSUE THREAD

**Issue by ggm-at-apnic** [Abhayakara/draft-tldr-sutld-ps#47]
I don't think section 4.3 summary is appropriately flagged for its importance. It should reflect more of the body of the text, and as a single paragraph matter of substance, should have more prominance in the document as a whole. It doesn't summarize the 'problem' at all.

**Comment by wkumari** [comment]
Ralph and I discussed by phone. Suggesting moving the entire "Summary" towards the top and folding it into Section 3

**Comment by ggm-at-apnic** [comment]
WFM.

**Comment by Abhayakara** [comment]
Consensus to move the summary in as an introduction to sec. 4.3.

**Comment by rdroms** [comment]
Edits completed.
