### ISSUE TITLE
4.1.2 cites sub-domains of .ARPA arguing for special use TLD

### ISSUE THREAD

**Issue by ggm-at-apnic** [Abhayakara/draft-tldr-sutld-ps#48]
It seems to me inappropriate to cite subdomains of .arpa which pre-existed the existence of ICANN to post-hoc justify the SUTLD problem statement

  * they are sub domains not TLD
  * they predate process in any sense.

note them? sure. do they help? nope.

So the promiscuous use of SUTLD distinct from SUDN means this is totally confused. It needs to be clearer.

**Comment by wkumari** [comment]
This is intended to be special use names problems, not special use TLD problems. 
Suggesting adding: 
A special-use name may be a name that should be resolved using the
     DNS protocol with no special handling.  An example of this is 'IN-
     ADDR.ARPA.' (this is an example of a special use name which is not a TLD)

... and will will further review / discuss.

**Comment by ggm-at-apnic** [comment]
ok. so partly, this response is a function of a document _name_ being sutld and then its _intent_ being more than special use TLD, which its name implies. If your "fix" is to point out the name of a document is not the same as its content or purpose I am content, in as much as the distinction is understood.

but I understand the problem to be almost quintessentially about TLD. The idea that we can resolve the problem by flagging sub-domains as special, and the consequences, radically alters the agenda because almost *all* of the cited problems excluding community acceptance go away if a sub-domain of an existing domain is used: the authority of the IETF->IAB->IANA chain to modify the behaviour under .arpa is not contestable, so most of the process issues regarding "qui bono" and "who decides" go away.

EG, alt.arpa is identified as the "doesn't exist in the dns" domain and all gethostby*() functions are required to be modified to DTRT, and unmodified legacy code stuck with NXDOMAIN as a consequence, thats an entirely different set of problems to "by what authority is ALT chosen and delegated, along side names who paid $150,000 to get their existence" question.

**Comment by Abhayakara** [comment]
consensus is to go with Warren's clarification

**Comment by rdroms** [comment]
Edits completed.
