### ISSUE TITLE
Should cite https://datatracker.ietf.org/liaison/1351/

### ISSUE THREAD

**Issue by ggm-at-apnic** [Abhayakara/draft-tldr-sutld-ps#49]
A note in the ALT github issues points to https://datatracker.ietf.org/liaison/1351/

I think this document should also cite this text. its highly informative of history leading to this situation. I couldn't see a citation to this.

**Comment by Abhayakara** [comment]
we have consensus to do this, probably as a 4.1.4 after the MoU.

**Comment by rdroms** [comment]
Suggested text:

4.1.4.  Liaison Statement on Technical Use of Domain Names

   As a result of processing requests to add names to the Special Use
   Domain Name registry, as documented in
   [I-D.chapin-additional-reserved-tlds] and
   [I-D.grothoff-iesg-special-use-p2p-names], the IAB a review of the
   process for adding names to the registry defined in RFC 6761.  This
   review was identified as in the charter of the IETF DNSOP working
   group, and the review has been conducted in that working group.  The
   Liaison Statement [SDO-IAB-ICANN-LS] notified ICANN of the review,
   affirmed that the discussion would be "open and transparent to
   participation by interested parties" and explicitly invited members
   of the ICANN community to participate.

   This document is a product of the IETF DNSOP working group review of
   the registry process in RFC 6761.

   [SDO-IAB-ICANN-LS]
              Internet Architecture Board, "Liaison Statement from the
              IAB to the ICANN Board on Technical Use of Domain Names",
              September 2015, <https://datatracker.ietf.org/
              liaison/1351>.

   [I-D.grothoff-iesg-special-use-p2p-names]
              Grothoff, C., Wachs, M., hellekin, h., Appelbaum, J., and
              L. Ryge, "Special-Use Domain Names of Peer-to-Peer
              Systems", draft-grothoff-iesg-special-use-p2p-names-04
              (work in progress), January 2015.

**Comment by Abhayakara** [comment]
lgtm.

**Comment by rdroms** [comment]
Oops, s/IAB a review/IAB initiated a review/

**Comment by Abhayakara** [comment]
meh. who verbs necessary?

**Comment by rdroms** [comment]
I'm going to go ahead and close this issue.  Warren, let me know if you think more needs to be done here.
