### ISSUE TITLE
Cheshire: don't just focus on names, also focus on behaviors

### ISSUE THREAD

**Issue by Abhayakara** [Abhayakara/draft-tldr-sutld-ps#5]
Stuart Cheshire: will make oblig comment abt special names doc that it focuses far too much on question of names, and not on behaviors.   here at the ietf we’re interested in writing software and how that sw behaves, and the use of names is a means to an end, we’ve discussed carrying around extra resolution context as tuple, nobody does that, could expand that API to have string+context and have a wg to debate context namespace ownership.   It doesn’t solve the problem.   Reconigizng that we can’t add layers without end, a single name has to be self-describing, and that means something about the name tells you how to look it up.   That technical point seems to be ignored by the special names document at present.

**Comment by wkumari** [comment]
We think that we have now addressed this. We discuss the resolution mechanism and resolution context. 
Please also #19....
Please reopen if not correct.
