### ISSUE TITLE
IETF precedence in special-use names registry.

### ISSUE THREAD

**Issue by Abhayakara** [Abhayakara/draft-tldr-sutld-ps#50]
OLD:
- No mechanism exists for adding a name to the registry without claiming that the IETF is responsible for that name, nor is it possible to state a precedence for the name, e.g. "if ICANN delegates this name, ICANN's delegation takes precedence."

NEW:
- The IETF may in some cases see the need to document that a name is in use without claiming that the use of the name is the IETF's use of the name.   No mechanism exists in the current registry to mark names in this way.

**Comment by Abhayakara** [comment]
consensus to make this change

**Comment by rdroms** [comment]
Note that the "OLD" text is also affected by issue #34.  Seems to me the right thing to do is insert the "NEW" text as a new bullet, leaving changes to the "OLD" text to issue #34.

**Comment by rdroms** [comment]
Edits completed.
