### ISSUE TITLE
Clarification in Introduction

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#51]
https://www.ietf.org/mail-archive/web/dnsop/current/msg19397.html

John Dickinson

"...When reading this document, care must
  be taken to not assume that the term Domain Name implies the
  particular protocol for resolving these names, the Domain Name System
  [RFC1034]. ..."

parses badly. Do you mean

"...When reading this document, care must
  be taken to not assume that the term Domain Name implies the use of the
  Domain Name System [RFC1034] for resolving these names. ..."?

**Comment by Abhayakara** [comment]
John's text seems better.

**Comment by rdroms** [comment]
I agree; I prefer John's text.

**Comment by Abhayakara** [comment]
Great!   Are you still editing, or do you need me to take over?

**Comment by rdroms** [comment]
> On Mar 7, 2017, at 9:49 PM, Ted Lemon <notifications@github.com> wrote:
> 
> Great! Are you still editing, or do you need me to take over?
> 
> 
I probably can't do any more editing until mid-day Thursday (3/9).  I have tentative text for #49 that I can push.

**Comment by rdroms** [comment]
I've made the edits and will close the issue.
