### ISSUE TITLE
New problem for section 3

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#56]
https://www.ietf.org/mail-archive/web/dnsop/current/msg19397.html

John Dickinson

Additional problem: The availability of special use names may encourage protocol
designers to design "bad" protocols.

**Comment by Abhayakara** [comment]
I think this isn't sufficiently clearly articulated to count as a statement of a problem.

**Comment by rdroms** [comment]
Consensus to agree with Ted; no changes made.
