### ISSUE TITLE
Document needs a "Security Considerations" section

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#57]

**Comment by rdroms** [comment]
Suggested text:

6.  Security Considerations

   There are security and privacy considerations associated with Domain
   Names, the DNS resolution system and other resolution systems used
   with Domain Names.  A few of these considerations are relevant to the
   problems with RFC 6761 listed in this document, as noted in the text.
   The most important considerations are related to possible attacks or
   loss of privacy related to misresolution of Domain Names by resolving
   or exposing those names through the incorrect resolution mechanism or
   resolution context.

**Comment by Abhayakara** [comment]
Hm, if you just say that, I think we're going to get dinged by the IESG: can you enumerate those important considerations, please?"   How about:

This document mentions various security and privacy considerations in the text.   However, this document creates no new security pr privacy concerns.

**Comment by rdroms** [comment]
That's better.  Less is more.

**Comment by rdroms** [comment]
I committed Ted's text but have left the issue open to remind us to confirm consensus.
