### ISSUE TITLE
Cheshire: without a process, we just have chaos

### ISSUE THREAD

**Issue by Abhayakara** [Abhayakara/draft-tldr-sutld-ps#6]
Other observation, two layers, api layer, application calls get hostbyname and friends, and then there is the protocol, and we assume those are tied together, but thye are not, /etc/host, netbios, mdns, .onion, nsswitch plugins in linux.  Without some mechanism we have chaos. 

DRC: ICANN has no opinion here, no assertion that anybody has to abide by anything ICANN says about this namespace.   2860 says IETF can reserve specific names for special uses and experimental uses.   My view of 6761 was a mech by which that could be exercised.   Nothing to do with new GTLD program.   The issue is that it creates a multipolar world.

**Comment by wkumari** [comment]
Ralph, Ted and Warren to chat. We'll attempt to add text saying that apps just call "resolution", not "resolution of context X".

**Comment by rdroms** [comment]
The problem here for sutld-ps is to point out that the application API and the specific resolution system API are two separate layers.

**Comment by Abhayakara** [comment]
OLD:
   o  There is demand for more than one name resolution protocol for
      Domain Names, but Domain Names contain no metadata to indicate
      which protocol to use to resolve them.
NEW:
   o  There is demand for more than one name resolution protocol for
      Domain Names.   Domain Names contain no metadata to indicate
      which protocol to use to resolve them.   Domain name resolution
      APIs do not provide a way to specify which protocol to use.

**Comment by rdroms** [comment]
Consensus on Ted's text.  Ralph to make edits.

**Comment by rdroms** [comment]
Edits complete.
