### ISSUE TITLE
Add new section "6. Summary"

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#60]
https://www.ietf.org/mail-archive/web/dnsop/current/msg19559.html

From Petr Špaček

I would like to comment on one side-effect of the changes:
The Summary section was removed and the text moved elsewhere. IMHO this
makes the document less understandable to a person who was not involved
with its development.

For this reason I propose new Summary section, which would be basically
current 4.1.4.  Liaison Statement on Technical Use of Domain Names.

The reference to these two I-Ds can be at the same place as current 4.1.4.

So the new text would look like:

4.1.4.  Expired Internet Drafts Relating to SUDN
  /links to/
  [I-D.chapin-additional-reserved-tlds]
  [I-D.grothoff-iesg-special-use-p2p-names]

6. Summary
  As a result of processing requests to add names to the Special-Use
  Domain Name registry, as documented in
  [I-D.chapin-additional-reserved-tlds] and
  [I-D.grothoff-iesg-special-use-p2p-names], the IAB initiated a review
  of the process defined in RFC 6761 for adding names to the registry.
  This review was identified as in the charter of the IETF DNSOP
  working group, and the review has been conducted in that working
  group.  The Liaison Statement [SDO-IAB-ICANN-LS] notified ICANN of
  the review, affirmed that the discussion would be "open and
  transparent to participation by interested parties" and explicitly
  invited members of the ICANN community to participate.
  This document is a product of the IETF DNSOP working group review of
  the registry process in RFC 6761.

I believe that original 4.1.4 nicely summarizes what this document is about.

**Comment by rdroms** [comment]
I think Petr makes a good point about one point - it would be helpful to expand on the way in which this document was chartered and the motivation.  I suggest adding a new third paragraph to the Introduction by moving text out of section 4.1.4:

The IAB initiated a review
of the process defined in RFC 6761 for adding names to the registry.
This review was identified as in the charter of the IETF DNSOP
working group, and the review has been conducted in that working
group. This document is a product of the IETF DNSOP working group review of
the registry process in RFC 6761.

In my opinion, section 4.1.4 mixes together the background on the liaison statement and the motivation for the review in dnsop.  Also, although the liaison statement just cites [I-D.chapin-additional-reserved-tlds] and [I-D.grothoff-iesg-special-use-p2p-names], there are other experiences with RFC 6761 that motivated the dnsop review and this document.  So, I think we want to bring that motivation out to the Introduction, but cite experience with RFC 6761 in general rather than just the two I-Ds.

**Comment by Abhayakara** [comment]
OK by me, although was it really the IAB that initiated the process?   Technically, the IAB can't initiate a review process, although they can certainly be the source of a request.   :)

**Comment by rdroms** [comment]
> On Mar 15, 2017, at 10:55 AM, Ted Lemon <notifications@github.com> wrote:
> 
> OK by me, although was it really the IAB that initiated the process? Technically, the IAB can't initiate a review process, although they can certainly be the source of a request. :)

Good point.  I will start a thread with us, Suz and Tim to get those details straightened out.

- Ralph

**Comment by moonshiner** [comment]
I would not put it in the main portion of the document, but I would opt for an Appendix discussing the other documents and the history. 

As for the initiation, it was the IAB, in concert with the IESG, that when DNSOP rechartered a few years back (and Mr. Lemon was quite detailed in his editorial pen on the rechartering text), that gave us #6 in the charter (in exchange for #5).

**Comment by Abhayakara** [comment]
Detailed?  Me?  :)

**Comment by moonshiner** [comment]
You were ultimately correct, and you did spend many cycles on Charter Items 5 and 6.   You must have blocked it out of your memory.

**Comment by rdroms** [comment]
In my opinion, the important point is that this document is a product of the dnsop WG review of the RFC 6761 processes and we don't need to go into a lot of detail in the history - nothing that would need an appendix or act as an authoritative source in the future.  How about this text for the introduction:

   The IETF DSNOP working group was chartered to conduct a review
   of the process for adding names to the registry that is defined in
   RFC 6761.   This document is a product of that review.

Then 4.1.4 becomes:

   As a result of processing requests to add names to the Special-Use
   Domain Name registry, as documented in
   [I-D.chapin-additional-reserved-tlds] and
   [I-D.grothoff-iesg-special-use-p2p-names], a review was chartered
   of the process defined in RFC 6761 for adding names to the registry (as explained earlier).
   The Liaison Statement [SDO-IAB-ICANN-LS] notified ICANN of
   the review, affirmed that the discussion would be "open and
   transparent to participation by interested parties" and explicitly
   invited members of the ICANN community to participate.

**Comment by moonshiner** [comment]
OK, you have convinced me.   I would say "the charter was expanded to review the process....:

**Comment by rdroms** [comment]
Tim - like this?

The IETF DSNOP working group charter was extended to include conducting a review
of the process for adding names to the registry that is defined in
RFC 6761. This document is a product of that review.

**Comment by moonshiner** [comment]
Excellent!

**Comment by rdroms** [comment]
Ted, Warren - if we have consensus on the proposed fix, I'll follow up with Petr on the dnsop mailing list.

**Comment by Abhayakara** [comment]
WFM

**Comment by rdroms** [comment]
Edited source and pushed to GitHub
