### ISSUE TITLE
Three step process (not just problem statement)

### ISSUE THREAD

**Issue by Abhayakara** [Abhayakara/draft-tldr-sutld-ps#7]
Three docs: problem, enmerate solutions, enumerate implications, _then_ pick solutions from the enumerated set.

Action: start a solutions document.

**Comment by wkumari** [comment]
Yes, let's work on a solutions document. However, the deadline approaches, so I thought let's focus on this for now and collect ALL proposed solutions.

**Comment by wkumari** [comment]
Closing because not applicable to *this* document.
