### ISSUE TITLE
meaning versus binding (Andrew McConachie)

### ISSUE THREAD

**Issue by Abhayakara** [Abhayakara/draft-tldr-sutld-ps#75]
The use of the term 'meaning' in this document is problematic. Meaning is something that humans do, not machines. What I believe we're actually interested in is scoping and binding. How a name is scoped and what object it gets bound to, not what it means.

For example the text:
"Domain Names with unambiguous global meaning are preferable to
Domain Names with local meaning which will be ambiguous.
Nevertheless both globally-meaningful and locally-special names
are in use and must be supported."

Should probably be changed to:
"Domain Names with unambiguous global bindings are preferable to
Domain Names with local bindings which will be ambiguous.
Nevertheless both globally-scoped and locally-scoped names
are in use and must be supported."

This is more akin to how programming language designers discuss this subject.[1] I don't want to delve into the usage of 'meaning' in RFC 2826 itself, but there are a couple other uses of 'meaning' in this I-D that I believe should be removed, and I am happy to send text if people agree.

**Comment by Abhayakara** [comment]
I committed the following change—Ralph and Warren, are you okay with this?

Section 4.1.1., paragraph 3:
OLD:

   o  The Internet requires a globally unique namespace

NEW:

   o  The Internet requires a globally unique namespace: a namespace in
      which any given name refers to the same information (has the same
      meaning) no matter who requests that information and no matter
      from which specific name server they request it.


Section 4.1.1., paragraph 4:
OLD:

   o  Private networks may operate private namespaces, but still require
      that names in the public namespace be globally unique.

NEW:

   o  Private networks may operate private namespaces, with names that
      have meanings only locally (within the private network) but still
      require that names in the public namespace be globally unique.

**Comment by rdroms** [comment]
That change is ok with me.

Thanks, Ted.

- Ralph

**Comment by Abhayakara** [comment]
Closing this since no further comment has been made and Benoit didn't object.  :)
