### ISSUE TITLE
Section 3 - clarify that problems are listed regardless of validity or ownership

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#76]
Benoit Claise AD review

https://mailarchive.ietf.org/arch/msg/dnsop/_ndo2HnuCIfftGlYkJLbYMZpUPc

    This section presents a list of problems that have been identified
    with respect to the assignment of Special-Use Domain Names.
    Solutions to these problems, including their costs or tradeoffs, are
    out of scope for this document.

    There is a broad diversity of opinion about this set of problems.
    Not every participant agrees that each of the problems enumerated in
    this document is actually a problem.  This document takes no position
    on the relative validity of the various problems that have been
    enumerated.  Its focused purposes are to enumerate those problems,
    provide the reader with context for thinking about them and provide a
    context for future discussion of solutions.

So you want to write something such as  ... regardless of whether the problems are valid ones AND regardless of the ownership (IETF, IANA, ICANN, or ...)
And it seems that you didn't try to categorize the problems per ownership (this is an IETF or ICANN problem, as an example).
I guess that this is the way you approached this document, right? You should document this.

**Comment by wkumari** [comment]
Proposed (and in the GH version):
"Not every participant agrees that each of the problems enumerated in
   this document is actually a problem.  This document takes no position
   on the relative validity of the various problems that have been
   enumerated, nor on the ownership (IETF, ICANN, IANA, some other
   group) of the problem. "

**Comment by Abhayakara** [comment]
I don't think that quite captures what Benoit was requesting.  I've made the following change to your change:

      This
      document takes no position on the relative validity of the various problems that have been
      enumerated, nor on the organization responsible for addressing the problem, if it is
      addressed.  The sole purposes of the document are to enumerate those problems, provide the
      reader with context for thinking about them and provide a context for future discussion of
      solutions, regardless of whether such solutions may be work for IETF, ICANN, IANA or some
      other group.

**Comment by Abhayakara** [comment]
s/the/each of the/

**Comment by Abhayakara** [comment]
s/each of the/each individual/ (so that it doesn't get read as there being one org responsible for all problems)

**Comment by rdroms** [comment]
> On Jun 6, 2017, at 3:06 PM, Ted Lemon <notifications@github.com> wrote:
> 
> I don't think that quite captures what Benoit was requesting. I've made the following change to your change:
> 
>   This
>   document takes no position on the relative validity of the various problems that have been
>   enumerated, nor on the organization responsible for addressing the problem, if it is
>   addressed.  The sole purposes of the document are to enumerate those problems, provide the
>   reader with context for thinking about them and provide a context for future discussion of
>   solutions, regardless of whether such solutions may be work for IETF, ICANN, IANA or some
>   other group.

Good catch.  I didn't read Benoit's comment as assigning ownership of solutions, but now that you point it out, it seems the sensible interpretation.

- Ralph

**Comment by rdroms** [comment]
Sorry to be dense...would you repost the entire text with your followup edits incorporated?

- Ralph

**Comment by Abhayakara** [comment]
NP.   Here it is:

      This
      document takes no position on the relative validity of the various problems that have been
      enumerated, nor on the organization responsible for addressing each individual problem, if it is
      addressed.  The sole purposes of the document are to enumerate those problems, provide the
      reader with context for thinking about them and provide a context for future discussion of
      solutions, regardless of whether such solutions may be work for IETF, ICANN, IANA or some
      other group.

**Comment by wkumari** [comment]
LGTM.

**Comment by rdroms** [comment]
OK with me
