### ISSUE TITLE
Section 4.2.7 - add citation of Errata correcting use of ".home" in RFC 7788

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#78]
Benoit Claise

https://mailarchive.ietf.org/arch/msg/dnsop/_ndo2HnuCIfftGlYkJLbYMZpUPc

correct the .home section in 4.2.7, which is solved with Errata ID: 4677

**Comment by wkumari** [comment]
Done, with:
"This was recognized as a mistake, and resulted in the publication of  an errata, [ERRATA-4677]."

**Comment by rdroms** [comment]
I think you made the following change along with this fix:

-   Name, RFC 7788 did not follow the process in RFC 6761 and request the
-   addition of ".home" to the IANA Special-Use Domain Name registry.
+   Name, RFC 7788 did not follow the process in RFC 6761 and requested
+   the addition of ".home" to the IANA Special-Use Domain Name registry.

This change is incorrect.  the mistake in RFC 778 is that it *did not* request the addition of .home to the SUDN Registry.

Alternative clarification (if one is needed):

Name, RFC 7788 did not follow the process in RFC 6761 and and did not request the
addition of ".home" to the IANA Special-Use Domain Name registry.

**Comment by Abhayakara** [comment]
I've wordsmithed even more:

RFC 7788 did not follow the process specified in RFC 6761: it did not request that ".home" be added to the IANA Special-Use Domain Name registry.

**Comment by rdroms** [comment]
> On Jun 6, 2017, at 2:50 PM, Ted Lemon <notifications@github.com> wrote:
> 
> I've wordsmithed even more:
> 
> RFC 7788 did not follow the process specified in RFC 6761: it did not request that ".home" be added to the IANA Special-Use Domain Name registry.

That wording is better; thanks.
