### ISSUE TITLE
Update reference to "Special-Use Domain Names registry" (?)

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#79]
Benoit Claise

https://mailarchive.ietf.org/arch/msg/dnsop/_ndo2HnuCIfftGlYkJLbYMZpUPc

    [SDO-ICANN-DAG]
               Internet Assigned Numbers Authority, "Special-Use Domain
               Names registry", October 2015,
               <https://newgtlds.icann.org/en/applicants/agb/guidebook- 
<https://newgtlds.icann.org/en/applicants/agb/guidebook-full-04jun12-en.pdf>
               full-04jun12-en.pdf 
<https://newgtlds.icann.org/en/applicants/agb/guidebook-full-04jun12-en.pdf>>

Don't you have a more up to date reference (2012)?
First page of this document is: "Currently the namespace consists of 22 gTLDs and over 250 ccTLDs operating on various models."

**Comment by wkumari** [comment]
Closing -- the lasted DAG is the 04 June 2012 version (thank gods!)
