### ISSUE TITLE
Cheshire: docs should say what name is used for, current icann doc does not

### ISSUE THREAD

**Issue by Abhayakara** [Abhayakara/draft-tldr-sutld-ps#8]
Stuart asks that I look at draft-cheshire-homenet-dothome illustrates the principle, not about don’t use this name, but what you should use this name for.   The reason not to is someone else is, or else to use it in this special way.  So positive definition, not negative exclusionary definitiions of non-things.

(Warren points out that there are legal implications to documenting things like this if one of the gtld applicants decided to take offense.)

**Comment by rdroms** [comment]
How do you think this principle ought to be added to the problem statement?  I don't see an immediate connection.

**Comment by wkumari** [comment]
Unclear what to do with this... Interesting meta comment, unclear if anything to add to PS doc.

**Comment by rdroms** [comment]
Consensus that there is nothing to add to PS doc.
