### ISSUE TITLE
Section 3 - Clarify citation of SDO-ICANN-COLL

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#80]
Benoit Claise

https://mailarchive.ietf.org/arch/msg/dnsop/_ndo2HnuCIfftGlYkJLbYMZpUPc

    o  There are several Domain Name TLDs that are in use without due
       process for a variety of purposes [SDO-ICANN-COLL 
<https://tools.ietf.org/html/draft-ietf-dnsop-sutld-ps-04#ref-SDO-ICANN-COLL>].  The status of
       these names need to be clarified and recorded to avoid future
       disputes about their use.

I don't understand the sentence "There are several Domain Name TLDs that are in use without due
       process for a variety of purposes", with a reference that speaks about "Name Collision in the DNS".

**Comment by wkumari** [comment]
Discussed. Think can close.

**Comment by Abhayakara** [comment]
Yup.
