### ISSUE TITLE
Bob Harold: extra "be used"

### ISSUE THREAD

**Issue by Abhayakara** [Abhayakara/draft-tldr-sutld-ps#82]
Last part of the last sentence:"they can only use the mDNS protocol be used for resolving that Domain Name."
Looks like "be used" is redundant and should be removed.

**Comment by Abhayakara** [comment]
I've updated the paragraph as follows (the text was a bit clunky, so I changed more than Bob suggested):

          One point to take from this is that there is already a
          requirement in RFC 6762 that when a stub resolver encounters the
          special label, '.LOCAL' at the top level of a domain name, it can
          only use the mDNS protocol to resolve that Domain
          Name.

**Comment by rdroms** [comment]
OK with me.

**Comment by wkumari** [comment]
And me :-)
