### ISSUE TITLE
Stephane Bortzmeyer: Use of the registry is inconsistent

### ISSUE THREAD

**Issue by Abhayakara** [Abhayakara/draft-tldr-sutld-ps#84]
> * Section 3 says "Use of the registry is inconsistent -- some
> Special-Use Domain Name RFCs specify registry entries, some don't;
> some specify delegation, some don't." There is no inconsistency
> here. RFC 6761 says (in its section 5) that the reservation of a
> Special-Use Domain Name is free to choose the rules regarding
> resolution, as long as they are properly explained.

How about the following change:

   o  Use of the registry is inconsistent -- some Special-Use Domain
      Name RFCs specifically add registry entries, some don't; some specify
      how and whether special-use name delegations should be done, 
      some don't.

**Comment by wkumari** [comment]
LGTM.

**Comment by rdroms** [comment]
OK with me.

**Comment by rdroms** [comment]
Changes committed.
