### ISSUE TITLE
Stephane Bortzmeyer: unilateral use

### ISSUE THREAD

**Issue by Abhayakara** [Abhayakara/draft-tldr-sutld-ps#85]
> * Section 4.2.2 says "the fact of its unilateral use by The Tor
> Project without following the RFC 6761 process" The onion TLD was in
> use in Tor since 2004, nine years before the publication of RFC
> 6761. It is grossly unfair to reproach not following an unpublished
> RFC. It was mentioned a long time ago
> <https://mailarchive.ietf.org/arch/msg/dnsop/nr4ECaVw6PT09o2xdM3jrKllHBI>

How about:

      The situation was somewhat forced, both by the fact of its
      unilateral use by The Tor Project before the RFC 6761
      process became available,

**Comment by Abhayakara** [comment]
Job Snijders suggests the following text, which I think is a definite improvement:

> NEW:
>   The situation was somewhat forced, both by the fact that use of the
>   .onion domain name by the Tor Project predates the process described
>   in RFC 6761 by 9 years, and because a deadline [CABF-DEADLINE] had
>   been set by the CA/Browser Forum [CABF] after which all PKI
>   certificates for internal names would expire and no new certificates
>   would be issued. At the time .onion was considered an internal name.
>   IETF recognition of the .onion as a Special-Use Top-Level Domain Name
>   facilitated the development of a certificate issuance process
>   specific to .onion domain names [CABF-BALLOT144]. 
> 
> [CABF-DEADLINE] should link to https://www.digicert.com/internal-names.htm
> [CABF] should link to https://cabforum.org/
> [CABF-BALLOT144] should link to https://cabforum.org/2015/02/18/ballot-144-validation-rules-dot-onion-names/

**Comment by wkumari** [comment]
Definite improvement. Feels like it could do with some minor readability word-smithing, but WFM. 
I'm not really sure I agree with "At the time .onion was considered an internal name" - by whom? what exactly is an internal name?

**Comment by Abhayakara** [comment]
Yeah, I also want to wordsmith it a little.   How about:

The situation was somewhat forced by several factors.  First, there was no process for allocating special-use domain names at the time that the .onion project started using the name, and since at the time the scope of use of the name was expected to be very constrained, the developers chose to allocate it unilaterally rather than asking the IETF or some other SDO to create a new process.   Second, the CA/Browser Forum [CABF] had set a deadline [CABF-DEADLINE] after which all PKI certificates for internal names, of which .onion is an example, would expire and no new certificates would be issued.   The IETF's designation of .onion as a Special-Use Top-Level Domain Name was needed to facilitate the development of a certificate issuance process specific to .onion domain names [CABF-BALLOT144].

**Comment by Abhayakara** [comment]
hm, could say "of which .onion was considered by them to be an example" to tease out more clearly the distinction you are suggesting, Warren.   Or, how about this:

For some time, the CA/Browser Forum [CABF] had been issuing certificates for what they referred to as "internal names."   Internal names are names allocated unilaterally for use in site-specific contexts.   Issuing certificates for such names came to be considered problematic, since no formal process for testing the validity of such names existed.   Consequently, CABF decided to phase out the use of such names in certificates, and set a deadline after which no new certs for such names would be issued [CABF-DEADLINE].   Because the .onion name had been allocated unilaterally, it was affected by this policy.   The IETF's designation ...

**Comment by Abhayakara** [comment]
Er, so the whole thing would read:

The situation was somewhat forced by several factors. First, there was no process for allocating special-use domain names at the time that the .onion project started using the name, and since at the time the scope of use of the name was expected to be very constrained, the developers chose to allocate it unilaterally rather than asking the IETF or some other SDO to create a new process. 

Second, for some time, the CA/Browser Forum [CABF] had been issuing certificates for what they referred to as "internal names." Internal names are names allocated unilaterally for use in site-specific contexts. Issuing certificates for such names came to be considered problematic, since no formal process for testing the validity of such names existed. Consequently, CABF decided to phase out the use of such names in certificates, and set a deadline after which no new certs for such names would be issued [CABF-DEADLINE]. Because the .onion name had been allocated unilaterally, it was affected by this policy.

The IETF's designation of .onion as a Special-Use Top-Level Domain Name was needed to facilitate the development of a certificate issuance process specific to .onion domain names [CABF-BALLOT144].

**Comment by rdroms** [comment]
Ted - are you intending the entire text in the immediately preceding comment to be contained in the second bullet of the bullet list?

"The situation was somewhat forced" seems awkward and not quite right to me.  How about "Devising a resolution to the situation was constrained by several factors."?

**Comment by rdroms** [comment]
Followup question on CABF policy - the text under consideration says what CABF was not going to do: issues certs for internal names.  Did they set rules as to what would be acceptable, and did those rules  compel The Tor Project to get a SUTLD designation for .onion?

**Comment by wkumari** [comment]
Yes, and yes.

From: https://cabforum.org/wp-content/uploads/Guidance-Deprecated-Internal-Names.pdf

Definitions:
Internal Server Name: A Server Name (which
may or may not include an Unregistered
Domain Name) that is not resolvable using the
public DNS.

As of the Effective Date of these
Requirements, prior to the issuance of
a Certificate with a Subject Alternative
Name (SAN) extension or Subject
Common Name field containing a
Reserved IP Address or Internal Server
Name, the CA SHALL notify the
Applicant that the use of such
Certificates has been deprecated by
the CA / Browser Forum and that the
practice will be eliminated by October
2016.


Also as of the Effective Date, the CA
SHALL NOT issue a certificate with an
Expiry Date later than 1 November
2015 with a SAN or Subject Common
Name field containing a Reserved IP
Address or Internal Server Name.


Effective 1 October 2016, CAs SHALL
revoke all unexpired Certificates whose
SAN or Subject Common Name field
contains a Reserved IP Address or
Internal Server Name.

**Comment by rdroms** [comment]
I edited in the new text but the commit failed with a conflict.  I'll try to resolve the issue later this AM.

Wasn't obvious to me what dates to use for:

[CABF-DEADLINE] should link to https://www.digicert.com/internal-names.htm
[CABF] should link to https://cabforum.org/

so I just put in today's date.  Any suggestions, esp. for www.digicert.com/internal-names.htm?

Finally, [SDO-CABF-INT] is no longer cited.  Should it be?

**Comment by rdroms** [comment]
Fixed the commit.  Issue is still open because of open questions.

**Comment by Abhayakara** [comment]
I just pushed a commit that re-inserts the reference to SDO-CABF-INT in the appropriate place.

**Comment by rdroms** [comment]
I added a note to the RFC Editor, asking for a fix for the missing date problem.
