### ISSUE TITLE
Bulleted list should be numbered, not unordered.

### ISSUE THREAD

**Issue by wkumari** [Abhayakara/draft-tldr-sutld-ps#88]
[ Issue opened for tracking purposes ]
While trying to reference some of the issues in the list of issues it became clear that they should be a numbered to facilitate referencing.

Creating and closing for tracking porpoises!

**Comment by rdroms** [comment]
Warren - this issue looks like it's still open?

**Comment by wkumari** [comment]
Whoops, apparently "Creating and closing for tracking porpoises!" was a bald-faced lie! 
"This time, for sure!"
