### ISSUE TITLE
Section 1, "believed to be complete"

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#89]
From IESG evaluation, Ben Campbell

Is there something to be gained by going out on the "believed to be complete" limb?

**Comment by rdroms** [comment]
Suggested edit:

OLD:

   This document presents a list, believed to be complete, of the
   problems associated with the assignment of Special-Use Domain Names.

NEW:

   This document presents a list, derived from a variety of sources
   including discussion in the IETF dnsop WG, of the problems
   associated with the assignment of Special-Use Domain Names.  The
   list is intended to be an unfiltered compilation of issues.

**Comment by suzworldwide** [comment]
WFM.


S.

**Comment by wkumari** [comment]
Resolved in commit d869ada   

(Gah, keyword parsing for referencing issues differs between GH and another system I use)
