### ISSUE TITLE
Section 4, add a reference

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#90]
From Alissa Cooper's IESG review:

In Section 4, "the IAB technical document" could use a reference.

**Comment by rdroms** [comment]
It appears the text in question is actually in section 5.  Suggested edit:

OLD:

   At the time of the writing of the IAB technical document,
   memories would have been fresh of the evolutionary process that led
   to the DNS' dominance as a protocol for Domain Name resolution.

NEW:

   At the time of the writing of the IAB technical document (RFC 2826),
   memories would have been fresh of the evolutionary process that led
   to the DNS' dominance as a protocol for Domain Name resolution.

Parentheses, not a formal citation, are intended.  I'm assuming RFC 2826 is the right document...

**Comment by wkumari** [comment]
Reference looks good, but I don't understand the "Parentheses, not a formal citation, are intended." -- why wouldn't we cite it?
