### ISSUE TITLE
Section 3, item 9.5: soften "will be used"

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#91]
From Spencer Dawkins' IESG review:

This text

        5.  If there is an IETF process through which a TLD can be
            assigned at zero cost other than time, this process will be
            used as an alternative to the more costly process of getting
            the name registered through ICANN.

seems extremely certain ("will be used"). Is that what you meant to say?

**Comment by rdroms** [comment]
I"m happy to leave in "will be used", and I have $10 to bet on its correctness.

**Comment by wkumari** [comment]
I think that we can close this one (there has been email thread)
