### ISSUE TITLE
Section 4.1: clarify text regarding which documents are IETF consensus documents

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#93]
From Spencer Dawkins' IESG review

Again, I'm assuming your intention is to give people something to think about. Given that, I wonder how badly you need the last sentence in 

4.1.  Primary Special-Use Domain Name Documents

>    The primary documents are considered primary because they directly
>    address the IETF's past thoughts on this topic in a general way, and
>    also because they describe what the IETF does in practice.  Only one
>    of these documents is an IETF consensus document.

You're pretty careful about pointing out whether each of the RFCs are consensus documents in the following subsections, and you provide enough explanation for the reader to know why the reader cares about each document. With the last sentence of 4.1 as lead-in, and no background because that comes later, document by document, I wouldn't take that section seriously.

I know that text is in Section 4.1, but "these documents" invited me to assume the same thing about the documents in Section 4.2 as well. If you need to keep the last sentence, you might consider

>    Only one
>    of the documents described in Section 4.1 is an IETF consensus document.

**Comment by Abhayakara** [comment]
I think it's fine to just delete that sentence.   I think it sprang out of my residual process-itis from having been an AD.   :)

**Comment by wkumari** [comment]
Resolved in commit e9d44ec.
