### ISSUE TITLE
Section 4.1.4: passive voice is to be avoided

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#94]
From Spencer Dawkins' IESG review

I know we publish a lot of passive voice text around here, but in 

4.1.4.  Liaison Statement on Technical Use of Domain Names

>    As a result of processing requests to add names to the Special-Use
>    Domain Name registry, as documented in
>    [I-D.chapin-additional-reserved-tlds] and
>    [I-D.grothoff-iesg-special-use-p2p-names], a review was chartered of
>    the process defined in RFC 6761 for adding names to the registry (as
>    explained earlier).  The Liaison Statement [SDO-IAB-ICANN-LS]
>    notified ICANN of the review, affirmed that the discussion would be
>    "open and transparent to participation by interested parties" and
>    explicitly invited members of the ICANN community to participate.

I am guessing who is requesting what, and who is performing the review, and who sent the liaison statement. Is this saying

>    When the IETF received processing requests to add names to the Special-Use
>    Domain Name registry, as documented in
>    [I-D.chapin-additional-reserved-tlds] and
>    [I-D.grothoff-iesg-special-use-p2p-names], the IETF chartered a review of
>    the process defined in RFC 6761 for adding names to the registry (as
>    explained earlier).  The IETF sent a Liaison Statement [SDO-IAB-ICANN-LS]
>    to ICANN to notify ICANN of the review, affirm that the discussion would be
>    "open and transparent to participation by interested parties" and
>    explicitly invite members of the ICANN community to participate.

? But, as I said, I'm guessing. I'm also not sure whether you want the reader to know the IETF sent a liaison to ICANN, and why, or whether you want the reader to look at the liaison statement text itself. If you want readers to look at the text, you might say what you hope readers find when they look.

**Comment by wkumari** [comment]
I like Spencer's text. I made a small edit (chartered ->began -- "chartered" seems more formal).

Good?


When the IETF received processing requests to add names to the Special-Use
Domain Name registry, as documented in
[I-D.chapin-additional-reserved-tlds] and
[I-D.grothoff-iesg-special-use-p2p-names], the IETF began a review of
the process defined in RFC 6761 for adding names to the registry (as
explained earlier). The IETF sent a Liaison Statement [SDO-IAB-ICANN-LS]
to ICANN to notify ICANN of the review, affirm that the discussion would be
"open and transparent to participation by interested parties" and
explicitly invite members of the ICANN community to participate.

**Comment by wkumari** [comment]
Actually, looking at the prior text, Spencer's unedited version is better then mine - using his.

**Comment by wkumari** [comment]
Resolved in commit  d869ada
