### ISSUE TITLE
Section 4.2.2: clarify how .onion was affected by CA/Browser Forum

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#95]
From Spencer Dawkins' IESG review:

I'm wondering how .onion was "affected" in this text,

>       Second, for some time, the CA/Browser Forum [SDO-CABF] had been
>       issuing certificates for what they referred to as "internal
>       names."  Internal names are names allocated unilaterally for use
>       in site-specific contexts.  Issuing certificates for such names
>       came to be considered problematic, since no formal process for
>       testing the validity of such names existed.  Consequently, CA/
>       Browser Forum decided to phase out the use of such names in
>       certificates [SDO-CABF-INT], and set a deadline after which no new
>       certificates for such names would be issued [SDO-CABF-DEADLINE].
>       Because the .onion name had been allocated unilaterally, it was
>       affected by this policy.
> 

Is this saying that existing certificates for .onion could not be renewed? Or that the nice .onion people planned to get certificates, and now they couldn't? Or something else? I'm guessing 

>       The IETF's designation of .onion as a Special-Use Top-Level Domain
>       Name was needed to facilitate the development of a certificate
>       issuance process specific to .onion domain names
>       [SDO-CABF-BALLOT144].
> 

is describing how .onion was affected, but I don't know if that's what was meant by "was affected", or something else.

**Comment by wkumari** [comment]
Perhaps: 
"Because the .onion name had been allocated unilaterally, this .onion names would not be eligible to obtain certificates." ?

**Comment by Abhayakara** [comment]
I think you could change the last sentence to "Because the .onion domain was allocated unilaterally, this would mean that certificates for subdomains of .onion could no longer be issued."
