### ISSUE TITLE
Section 5: clarify "picking an unused TLD"

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#96]
From Spencer Dawkins' IESG review

If I'm tracking what I'm reading, 

>    The Sun Microsystems model of having private domains within a
>    corporate site, while supporting the global Domain Name system for
>    off-site, persisted even after the NIS protocol fell into disuse.
>    Microsoft used to recommend that site administrators use a "private"
>    TLD for internal use, and this practice was very much a part of the
>    zeitgeist at the time (see section 5.1 of [SDO-ICANN-COLL] and
>    Appendix G of [RFC6762]).  This attitude is at the root of the
>    widespread practice of simply picking an unused TLD and using it for
>    experimental purposes, which persists even at the time of writing of
>    this memo.
> 

it might be more accurate to say "simply picking an apparently-unused TLD".

**Comment by wkumari** [comment]
Yup, sounds correct to me...

**Comment by wkumari** [comment]
Closed in editor version.
