### ISSUE TITLE
Add SUDN and MoU to terminology section

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#97]
From Mirja Kühlewind's IESG review

I guess SUDN (registry) and MoU could be added to the terminology section.

**Comment by rdroms** [comment]
There is an instance of "SUDN" in section 4.2.6 that we missed - in issue #43 we decided to spell out SUDN throughout the document.

"MoU" is only used in section 4.1.3.  We could simply add the definition as a parenthetical.  At the same time, we might want to expand MoU in the section title:

OLD:

4.1.3.  MoU Concerning the Technical Work of the IANA

   There exists a Memorandum of Understanding [RFC2860] between the IETF
   and ICANN (Internet Corporation for Assigned Names and Numbers) which
   discusses how names and numbers will be managed through the IANA
   (Internet Assigned Numbers Authority).

NEW:

4.1.3.  Memorandum of Understanding Concerning the Technical Work of the IANA

   There exists a Memorandum of Understanding (MoU) [RFC2860] between the IETF
   and ICANN (Internet Corporation for Assigned Names and Numbers) which
   discusses how names and numbers will be managed through the IANA
   (Internet Assigned Numbers Authority).

**Comment by wkumari** [comment]
Resolved in editor version.

**Comment by rdroms** [comment]
Warren - I think you might not have fixed this part of #97:

   There is an instance of "SUDN" in section 4.2.6 that we missed - in issue #43 we decided to spell out SUDN throughout the document.

From section 4.2.6:

   to the Special-Use Domain Names registry.  This appears to have
   happened because the document did not explicitly request the addition
   of an entry for "ipv4only.arpa" in the SUDN registry.  This is an

Unless you have a reason for not making that change, I can go ahead with the (very small) update.

- Ralph

**Comment by wkumari** [comment]
Nope, was an oversight -- I accidentally searched for SUTLD, not SUDN. 
"This time for sure!"
