### ISSUE TITLE
Retitle doc as "Issues, Concerns, and information related to Special-Use Domain Names"

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#98]
From Terry Manderson's IESG review

Thanks for writing this document - I believe that having such a document makes future discussions much easier, that said I am not a fan of publishing problem statements in the RFC series. Given the document already lays out a level of dissent in so far as some people don't see all these listed "problems" as problems, (and I agree with them!) - they could however be universally described as "issues", where any particular concern or issue doesn't necessarily need to a response (irrespective of which forum or SDO holds the baton for that discussion piece). My suggestion would be to reword language portions to describe the information contained in this draft as "issues and concerns" and further because the text provided covers more than just the enumerated set of "issues" (was problems), may I also suggest a title change to something like "Issues, Concerns, and information related to Special-Use Domain Names".

**Comment by Abhayakara** [comment]
I believe that you are the only one who didn't weigh in on this, Ralph, but among the other guilty parties, we concluded that this change would go well beyond the working group consensus, and isn't practical anyway.

**Comment by rdroms** [comment]
I recall the thread, and I recall agreeing at the time (I know I meant to respond but might not have).

So, I hear consensus to close without making any changes.
