### ISSUE TITLE
Light edit of the Acknowledgments section

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#99]
From Suzanne Woolf

Not to be obnoxious, but I do want to suggest a light edit of the Acknowledgments section of the sutld-ps doc. It’s a little excessively flippant, and it leaves out a couple of people who made substantive contributions on a contentious topic (admittedly including me).

The audience for this document is slightly wider than usual, so I suspect we should proceed accordingly.

**Comment by suzworldwide** [comment]
I assume misspelling my name is not an editorial comment :-P

**Comment by rdroms** [comment]
Erp.  Fixed in original issue...

**Comment by suzworldwide** [comment]
LOL....It's all good. :-)

**Comment by wkumari** [comment]
I changed this to be:
```
Mark Andrews, Stuart Cheshire, David Conrad, Paul Ebersman, Aaron Falk and Suzanne Woolf all made helpful and insightful observations or patiently answered questions. This should not be taken as an indication that any of these folks actually agree with what the document says, but their generosity with time and thought are appreciated in any case.
Stephane Bortzmeyer, John Dickinson, Bob Harold, Paul Hoffman, Russ Housley, Joel Jaeggli, Andrew McConachie, George Michaelson, Petr Spacek and others provided significant review and / or useful comments.
This document also owes a great deal to Ed Lewis' excellent work on what a "Domain Name" is.
```
I went through the Issues and added additional people who had made larger contributions - it's possible I missed some people (hence the "and others").

**Comment by Abhayakara** [comment]
This is great, thanks for doing the research!

**Comment by rdroms** [comment]
Yes ... thanks and I agree with the new text.
